// AUTO-GENERATED from Catering_Dish_Bank.xlsx — do not edit by hand.
// 767 dishes across 21 categories, each flagged Veg / Non-Veg.
// To regenerate, re-run the Excel import against an updated dish bank.

export interface Dish { id: number; section: string; name: string; veg: 'Veg' | 'Non-Veg' }

/** Catering menu categories, in display order — sourced from the dish bank Excel. */
export const MENU_SECTIONS = ['Welcome Drink', 'Soup (Veg)', 'Soup (Non-Veg)', 'Veg Starter', 'Non-Veg Starter', 'Salad', 'Veg Curry', 'Dal', 'Veg Rice / Biryani / Pulao', 'Non-Veg Biryani', 'Non-Veg Curry', 'Indian Bread', 'Raitha', 'Chutney', 'Rasam / Pulusu', 'Sweet / Dessert', 'Ice Cream', 'Fresh Fruit', 'Common Items / Accompaniments', 'Live Counter / Station', 'Add-On (Extra Charge)'] as const

export const DISH_BANK: Dish[] = [
  { id: 1, section: 'Welcome Drink', name: 'Assorted Flavoured Juice', veg: 'Veg' },
  { id: 2, section: 'Welcome Drink', name: 'Assorted Soft Drink', veg: 'Veg' },
  { id: 3, section: 'Welcome Drink', name: 'Badam Milk (Hot/Cold)', veg: 'Veg' },
  { id: 4, section: 'Welcome Drink', name: 'Blue Lagoon', veg: 'Veg' },
  { id: 5, section: 'Welcome Drink', name: 'Butter Milk', veg: 'Veg' },
  { id: 6, section: 'Welcome Drink', name: 'Cranberry Cooler', veg: 'Veg' },
  { id: 7, section: 'Welcome Drink', name: 'Fresh Fruit Juice', veg: 'Veg' },
  { id: 8, section: 'Welcome Drink', name: 'Fresh Lime Juice', veg: 'Veg' },
  { id: 9, section: 'Welcome Drink', name: 'Fruit Juice', veg: 'Veg' },
  { id: 10, section: 'Welcome Drink', name: 'Fruit Punch', veg: 'Veg' },
  { id: 11, section: 'Welcome Drink', name: 'Guava Delight', veg: 'Veg' },
  { id: 12, section: 'Welcome Drink', name: 'Khus Sarbat', veg: 'Veg' },
  { id: 13, section: 'Welcome Drink', name: 'Lassi', veg: 'Veg' },
  { id: 14, section: 'Welcome Drink', name: 'Litchi Delight', veg: 'Veg' },
  { id: 15, section: 'Welcome Drink', name: 'Mango Colada', veg: 'Veg' },
  { id: 16, section: 'Welcome Drink', name: 'Mango Milkshake', veg: 'Veg' },
  { id: 17, section: 'Welcome Drink', name: 'Mango Panna', veg: 'Veg' },
  { id: 18, section: 'Welcome Drink', name: 'Mint & Rose Cooler', veg: 'Veg' },
  { id: 19, section: 'Welcome Drink', name: 'Mixed Fruit Juice', veg: 'Veg' },
  { id: 20, section: 'Welcome Drink', name: 'Nimbu Pani', veg: 'Veg' },
  { id: 21, section: 'Welcome Drink', name: 'Orange Blossom', veg: 'Veg' },
  { id: 22, section: 'Welcome Drink', name: 'Pineapple Juice', veg: 'Veg' },
  { id: 23, section: 'Welcome Drink', name: 'Pineapple Punch', veg: 'Veg' },
  { id: 24, section: 'Welcome Drink', name: 'Strawberry Blonde', veg: 'Veg' },
  { id: 25, section: 'Welcome Drink', name: 'Strawberry Milkshake', veg: 'Veg' },
  { id: 26, section: 'Welcome Drink', name: 'Thandai', veg: 'Veg' },
  { id: 27, section: 'Welcome Drink', name: 'Vanilla Milkshake', veg: 'Veg' },
  { id: 28, section: 'Welcome Drink', name: 'Virgin Pinacolada', veg: 'Veg' },
  { id: 29, section: 'Welcome Drink', name: 'Watermelon Juice', veg: 'Veg' },
  { id: 30, section: 'Welcome Drink', name: 'Watermelon Milkshake', veg: 'Veg' },
  { id: 31, section: 'Soup (Veg)', name: 'Badam Subz Ka Shorba', veg: 'Veg' },
  { id: 32, section: 'Soup (Veg)', name: 'Corn Chowder', veg: 'Veg' },
  { id: 33, section: 'Soup (Veg)', name: 'Cream Of Broccoli Soup', veg: 'Veg' },
  { id: 34, section: 'Soup (Veg)', name: 'Cream Of Cauliflower Soup', veg: 'Veg' },
  { id: 35, section: 'Soup (Veg)', name: 'Cream Of Ginger And Carrot Soup', veg: 'Veg' },
  { id: 36, section: 'Soup (Veg)', name: 'Cream Of Green Peas Soup', veg: 'Veg' },
  { id: 37, section: 'Soup (Veg)', name: 'Cream Of Mushroom Soup', veg: 'Veg' },
  { id: 38, section: 'Soup (Veg)', name: 'Cream Of Oven Roasted Tomatoes And Garlic Soup', veg: 'Veg' },
  { id: 39, section: 'Soup (Veg)', name: 'Cream Of Spinach Soup', veg: 'Veg' },
  { id: 40, section: 'Soup (Veg)', name: 'Cream Of Tomato Soup', veg: 'Veg' },
  { id: 41, section: 'Soup (Veg)', name: 'Cream Of Veg Soup', veg: 'Veg' },
  { id: 42, section: 'Soup (Veg)', name: 'Creamy Pumpkin And Roasted Garlic Soup', veg: 'Veg' },
  { id: 43, section: 'Soup (Veg)', name: 'Dal Dhaniya Shorba', veg: 'Veg' },
  { id: 44, section: 'Soup (Veg)', name: 'Dal Shorba', veg: 'Veg' },
  { id: 45, section: 'Soup (Veg)', name: 'Dhania Shorba', veg: 'Veg' },
  { id: 46, section: 'Soup (Veg)', name: 'Hot & Sour Vegetable Soup', veg: 'Veg' },
  { id: 47, section: 'Soup (Veg)', name: 'Hot N Sour Vegetable Soup', veg: 'Veg' },
  { id: 48, section: 'Soup (Veg)', name: 'Italian Minestrone Soup', veg: 'Veg' },
  { id: 49, section: 'Soup (Veg)', name: 'Kesari Dal Dum Shorba', veg: 'Veg' },
  { id: 50, section: 'Soup (Veg)', name: 'Leek And Lentil Soup', veg: 'Veg' },
  { id: 51, section: 'Soup (Veg)', name: 'Lemon Coriander Soup', veg: 'Veg' },
  { id: 52, section: 'Soup (Veg)', name: 'Manchow Vegetable Soup', veg: 'Veg' },
  { id: 53, section: 'Soup (Veg)', name: 'Minestrone Soup', veg: 'Veg' },
  { id: 54, section: 'Soup (Veg)', name: 'Mixed Vegetable Broth', veg: 'Veg' },
  { id: 55, section: 'Soup (Veg)', name: 'Mulligatawny Soup', veg: 'Veg' },
  { id: 56, section: 'Soup (Veg)', name: 'Palak Aur Hara Channe Ka Shorba', veg: 'Veg' },
  { id: 57, section: 'Soup (Veg)', name: 'Roast Vegetable Soup', veg: 'Veg' },
  { id: 58, section: 'Soup (Veg)', name: 'Sweet Corn Veg Soup', veg: 'Veg' },
  { id: 59, section: 'Soup (Veg)', name: 'Tamatar Dhaniya Shorba', veg: 'Veg' },
  { id: 60, section: 'Soup (Veg)', name: 'Tamatar Shorba', veg: 'Veg' },
  { id: 61, section: 'Soup (Veg)', name: 'Tom Yum Veg Soup', veg: 'Veg' },
  { id: 62, section: 'Soup (Veg)', name: 'Tomato Basil Soup', veg: 'Veg' },
  { id: 63, section: 'Soup (Veg)', name: 'Tomato Shorba', veg: 'Veg' },
  { id: 64, section: 'Soup (Veg)', name: 'Veg Clear Soup', veg: 'Veg' },
  { id: 65, section: 'Soup (Veg)', name: 'Veg Corn Soup', veg: 'Veg' },
  { id: 66, section: 'Soup (Veg)', name: 'Veg Hot & Sour Soup', veg: 'Veg' },
  { id: 67, section: 'Soup (Veg)', name: 'Veg Manchow Soup', veg: 'Veg' },
  { id: 68, section: 'Soup (Veg)', name: 'Veg Tulumein Soup', veg: 'Veg' },
  { id: 69, section: 'Soup (Veg)', name: 'Vegetable Clear Soup', veg: 'Veg' },
  { id: 70, section: 'Soup (Veg)', name: 'Vegetable Coriander Soup', veg: 'Veg' },
  { id: 71, section: 'Soup (Veg)', name: 'Vegetable Manchow Soup', veg: 'Veg' },
  { id: 72, section: 'Soup (Veg)', name: 'Vegetable Noodles Soup', veg: 'Veg' },
  { id: 73, section: 'Soup (Non-Veg)', name: 'Asian Noodle Chicken Soup', veg: 'Veg' },
  { id: 74, section: 'Soup (Non-Veg)', name: 'Asian Thukpa Chicken Soup', veg: 'Veg' },
  { id: 75, section: 'Soup (Non-Veg)', name: 'Chicken Cantonese Soup', veg: 'Veg' },
  { id: 76, section: 'Soup (Non-Veg)', name: 'Chicken Clear Soup', veg: 'Veg' },
  { id: 77, section: 'Soup (Non-Veg)', name: 'Chicken Corn Soup', veg: 'Veg' },
  { id: 78, section: 'Soup (Non-Veg)', name: 'Chicken Hot & Sour Soup', veg: 'Veg' },
  { id: 79, section: 'Soup (Non-Veg)', name: 'Chicken Manchow Soup', veg: 'Veg' },
  { id: 80, section: 'Soup (Non-Veg)', name: 'Chicken Noodles Soup', veg: 'Veg' },
  { id: 81, section: 'Soup (Non-Veg)', name: 'Chooza-E-Dhaniya Shorba', veg: 'Veg' },
  { id: 82, section: 'Soup (Non-Veg)', name: 'Corn And Prawn Chowder', veg: 'Veg' },
  { id: 83, section: 'Soup (Non-Veg)', name: 'Cream Of Chicken Soup', veg: 'Veg' },
  { id: 84, section: 'Soup (Non-Veg)', name: 'Fish Coriander Spicy Soup', veg: 'Veg' },
  { id: 85, section: 'Soup (Non-Veg)', name: 'Hot N Sour Chicken Soup', veg: 'Veg' },
  { id: 86, section: 'Soup (Non-Veg)', name: 'Khumb Aur Murgh Ka Shorba', veg: 'Veg' },
  { id: 87, section: 'Soup (Non-Veg)', name: 'Leek And Lentil With Fish Soup', veg: 'Veg' },
  { id: 88, section: 'Soup (Non-Veg)', name: 'Lemon Coriander Chicken Soup', veg: 'Veg' },
  { id: 89, section: 'Soup (Non-Veg)', name: 'Manchow Chicken Soup', veg: 'Veg' },
  { id: 90, section: 'Soup (Non-Veg)', name: 'Minestrone Chicken Soup', veg: 'Veg' },
  { id: 91, section: 'Soup (Non-Veg)', name: 'Mulligatawny Chicken Soup', veg: 'Veg' },
  { id: 92, section: 'Soup (Non-Veg)', name: 'Murgh Adraki Shorba', veg: 'Veg' },
  { id: 93, section: 'Soup (Non-Veg)', name: 'Murgh Aur Subz Shorba', veg: 'Veg' },
  { id: 94, section: 'Soup (Non-Veg)', name: 'Murgh Badami Shorba', veg: 'Veg' },
  { id: 95, section: 'Soup (Non-Veg)', name: 'Murgh Shorba', veg: 'Veg' },
  { id: 96, section: 'Soup (Non-Veg)', name: 'Murgh Zafrani Shorba', veg: 'Veg' },
  { id: 97, section: 'Soup (Non-Veg)', name: 'Roast Lamb Soup', veg: 'Veg' },
  { id: 98, section: 'Soup (Non-Veg)', name: 'Sweet Corn Chicken Soup', veg: 'Veg' },
  { id: 99, section: 'Soup (Non-Veg)', name: 'Thai Tom Yom Kai Soup', veg: 'Veg' },
  { id: 100, section: 'Soup (Non-Veg)', name: 'Thyme Scented Chicken And Pumpkin Soup', veg: 'Veg' },
  { id: 101, section: 'Veg Starter', name: 'Aloo 65', veg: 'Veg' },
  { id: 102, section: 'Veg Starter', name: 'Aloo Adraki Tikki', veg: 'Veg' },
  { id: 103, section: 'Veg Starter', name: 'Aloo Aur Makai Ki Tikki', veg: 'Veg' },
  { id: 104, section: 'Veg Starter', name: 'Aloo Kaju Bullets', veg: 'Veg' },
  { id: 105, section: 'Veg Starter', name: 'Aloo Pudina Ki Tikki', veg: 'Veg' },
  { id: 106, section: 'Veg Starter', name: 'Aloo Shikampuri', veg: 'Veg' },
  { id: 107, section: 'Veg Starter', name: 'Angoori Paneer Kebab', veg: 'Veg' },
  { id: 108, section: 'Veg Starter', name: 'Anjeer Aur Kacche Kele Ki Tikki', veg: 'Veg' },
  { id: 109, section: 'Veg Starter', name: 'Baby Corn Salt And Pepper', veg: 'Veg' },
  { id: 110, section: 'Veg Starter', name: 'Badami Subz Ki Tikki', veg: 'Veg' },
  { id: 111, section: 'Veg Starter', name: 'Butte Ka Kebab', veg: 'Veg' },
  { id: 112, section: 'Veg Starter', name: 'Chilli Baby Corn', veg: 'Veg' },
  { id: 113, section: 'Veg Starter', name: 'Chilli Paneer', veg: 'Veg' },
  { id: 114, section: 'Veg Starter', name: 'Chilli Potato Garlic Balls', veg: 'Veg' },
  { id: 115, section: 'Veg Starter', name: 'Cocktail Samosa', veg: 'Veg' },
  { id: 116, section: 'Veg Starter', name: 'Crispy Fried Paneer In Hot Garlic Sauce', veg: 'Veg' },
  { id: 117, section: 'Veg Starter', name: 'Crispy Salt And Pepper Vegetable', veg: 'Veg' },
  { id: 118, section: 'Veg Starter', name: 'Crispy Vegetable', veg: 'Veg' },
  { id: 119, section: 'Veg Starter', name: 'Crispy Vegetable Salt & Pepper', veg: 'Veg' },
  { id: 120, section: 'Veg Starter', name: 'Cut Mirchi Bajji', veg: 'Veg' },
  { id: 121, section: 'Veg Starter', name: 'Dahi Ke Kebab', veg: 'Veg' },
  { id: 122, section: 'Veg Starter', name: 'Falafel', veg: 'Veg' },
  { id: 123, section: 'Veg Starter', name: 'French Fries', veg: 'Veg' },
  { id: 124, section: 'Veg Starter', name: 'Gilafi Hariyali Subz Ki Seekh', veg: 'Veg' },
  { id: 125, section: 'Veg Starter', name: 'Gobi 65', veg: 'Veg' },
  { id: 126, section: 'Veg Starter', name: 'Gobi Manchurian', veg: 'Veg' },
  { id: 127, section: 'Veg Starter', name: 'Golden Fried Baby Corn', veg: 'Veg' },
  { id: 128, section: 'Veg Starter', name: 'Hara Bhara Kebab', veg: 'Veg' },
  { id: 129, section: 'Veg Starter', name: 'Harabara Kebab', veg: 'Veg' },
  { id: 130, section: 'Veg Starter', name: 'Hariyali Anjeer Ki Tikki', veg: 'Veg' },
  { id: 131, section: 'Veg Starter', name: 'Honey Chilli Crispy Potato', veg: 'Veg' },
  { id: 132, section: 'Veg Starter', name: 'Honey Chilly Potato', veg: 'Veg' },
  { id: 133, section: 'Veg Starter', name: 'Jaituni Paneer Tikka', veg: 'Veg' },
  { id: 134, section: 'Veg Starter', name: 'Kalonji Makai Ki Tikki', veg: 'Veg' },
  { id: 135, section: 'Veg Starter', name: 'Karivepaku Baby Corn', veg: 'Veg' },
  { id: 136, section: 'Veg Starter', name: 'Makai Ki Shammi', veg: 'Veg' },
  { id: 137, section: 'Veg Starter', name: 'Masala Dal Vada', veg: 'Veg' },
  { id: 138, section: 'Veg Starter', name: 'Methi Corn Ki Chatpati Seekh', veg: 'Veg' },
  { id: 139, section: 'Veg Starter', name: 'Mini Samosa', veg: 'Veg' },
  { id: 140, section: 'Veg Starter', name: 'Mirchi Bajji', veg: 'Veg' },
  { id: 141, section: 'Veg Starter', name: 'Mixed Dal Wada', veg: 'Veg' },
  { id: 142, section: 'Veg Starter', name: 'Mushroom Salt & Pepper', veg: 'Veg' },
  { id: 143, section: 'Veg Starter', name: 'Onion Pakoda', veg: 'Veg' },
  { id: 144, section: 'Veg Starter', name: 'Onion Pakoras', veg: 'Veg' },
  { id: 145, section: 'Veg Starter', name: 'Palak Aur Anardhana Ki Tikki', veg: 'Veg' },
  { id: 146, section: 'Veg Starter', name: 'Paneer 65', veg: 'Veg' },
  { id: 147, section: 'Veg Starter', name: 'Paneer Hong Kong Style', veg: 'Veg' },
  { id: 148, section: 'Veg Starter', name: 'Paneer Salt & Pepper', veg: 'Veg' },
  { id: 149, section: 'Veg Starter', name: 'Paneer Tikka', veg: 'Veg' },
  { id: 150, section: 'Veg Starter', name: 'Paneer Tikka Shashlik', veg: 'Veg' },
  { id: 151, section: 'Veg Starter', name: 'Potato Cheese Balls', veg: 'Veg' },
  { id: 152, section: 'Veg Starter', name: 'Potato Cheese Shots', veg: 'Veg' },
  { id: 153, section: 'Veg Starter', name: 'Sesame Fried Vegetables', veg: 'Veg' },
  { id: 154, section: 'Veg Starter', name: 'Shanghai Rolls', veg: 'Veg' },
  { id: 155, section: 'Veg Starter', name: 'Stuffed Fried Mushrooms', veg: 'Veg' },
  { id: 156, section: 'Veg Starter', name: 'Subz Galouti', veg: 'Veg' },
  { id: 157, section: 'Veg Starter', name: 'Subz Shikampur', veg: 'Veg' },
  { id: 158, section: 'Veg Starter', name: 'Tandoori Aloo', veg: 'Veg' },
  { id: 159, section: 'Veg Starter', name: 'Tandoori Gobi', veg: 'Veg' },
  { id: 160, section: 'Veg Starter', name: 'Tandoori Khumb', veg: 'Veg' },
  { id: 161, section: 'Veg Starter', name: 'Tawa Paneer', veg: 'Veg' },
  { id: 162, section: 'Veg Starter', name: 'Thai Corn Cakes', veg: 'Veg' },
  { id: 163, section: 'Veg Starter', name: 'Veg Bullets', veg: 'Veg' },
  { id: 164, section: 'Veg Starter', name: 'Veg Gold Coin', veg: 'Veg' },
  { id: 165, section: 'Veg Starter', name: 'Veg Lollypop', veg: 'Veg' },
  { id: 166, section: 'Veg Starter', name: 'Veg Manchurian Dry', veg: 'Veg' },
  { id: 167, section: 'Veg Starter', name: 'Veg Nuggets', veg: 'Veg' },
  { id: 168, section: 'Veg Starter', name: 'Veg Samosa', veg: 'Veg' },
  { id: 169, section: 'Veg Starter', name: 'Veg Shanghai Roll', veg: 'Veg' },
  { id: 170, section: 'Veg Starter', name: 'Veg Spring Roll', veg: 'Veg' },
  { id: 171, section: 'Veg Starter', name: 'Vegetable Croquettes', veg: 'Veg' },
  { id: 172, section: 'Veg Starter', name: 'Vegetable Pakoras', veg: 'Veg' },
  { id: 173, section: 'Veg Starter', name: 'Vegetable Shammi Kebab', veg: 'Veg' },
  { id: 174, section: 'Veg Starter', name: 'Vegetable Wonton With Chilly Dip', veg: 'Veg' },
  { id: 175, section: 'Non-Veg Starter', name: 'Amritsari Fish Fry', veg: 'Veg' },
  { id: 176, section: 'Non-Veg Starter', name: 'Andhra Fried Fish', veg: 'Veg' },
  { id: 177, section: 'Non-Veg Starter', name: 'Apollo Fish', veg: 'Veg' },
  { id: 178, section: 'Non-Veg Starter', name: 'Beer Batter Fish', veg: 'Veg' },
  { id: 179, section: 'Non-Veg Starter', name: 'Butter Milk Soaked Fish Poppers', veg: 'Veg' },
  { id: 180, section: 'Non-Veg Starter', name: 'Chicken 65', veg: 'Veg' },
  { id: 181, section: 'Non-Veg Starter', name: 'Chicken Croquettes', veg: 'Veg' },
  { id: 182, section: 'Non-Veg Starter', name: 'Chicken Lollipops', veg: 'Veg' },
  { id: 183, section: 'Non-Veg Starter', name: 'Chicken Majestic', veg: 'Veg' },
  { id: 184, section: 'Non-Veg Starter', name: 'Chicken Manchurian', veg: 'Veg' },
  { id: 185, section: 'Non-Veg Starter', name: 'Chicken Nuggets', veg: 'Veg' },
  { id: 186, section: 'Non-Veg Starter', name: 'Chicken Pakoda', veg: 'Veg' },
  { id: 187, section: 'Non-Veg Starter', name: 'Chicken Pepper Fry', veg: 'Veg' },
  { id: 188, section: 'Non-Veg Starter', name: 'Chicken Salt And Pepper', veg: 'Veg' },
  { id: 189, section: 'Non-Veg Starter', name: 'Chicken Samosa', veg: 'Veg' },
  { id: 190, section: 'Non-Veg Starter', name: 'Chicken Satay', veg: 'Veg' },
  { id: 191, section: 'Non-Veg Starter', name: 'Chicken Sukka', veg: 'Veg' },
  { id: 192, section: 'Non-Veg Starter', name: 'Chicken Tikka', veg: 'Veg' },
  { id: 193, section: 'Non-Veg Starter', name: 'Chilli Chicken', veg: 'Veg' },
  { id: 194, section: 'Non-Veg Starter', name: 'Chilly Fish', veg: 'Veg' },
  { id: 195, section: 'Non-Veg Starter', name: 'Fish & Chips', veg: 'Veg' },
  { id: 196, section: 'Non-Veg Starter', name: 'Fish Fry', veg: 'Veg' },
  { id: 197, section: 'Non-Veg Starter', name: 'Fish Salt & Pepper', veg: 'Veg' },
  { id: 198, section: 'Non-Veg Starter', name: 'Fish Salt And Pepper', veg: 'Veg' },
  { id: 199, section: 'Non-Veg Starter', name: 'Fish Tikka', veg: 'Veg' },
  { id: 200, section: 'Non-Veg Starter', name: 'Fish With Hot Basil', veg: 'Veg' },
  { id: 201, section: 'Non-Veg Starter', name: 'Garlic Fish', veg: 'Veg' },
  { id: 202, section: 'Non-Veg Starter', name: 'Karepaku Rawa Fried Fish', veg: 'Veg' },
  { id: 203, section: 'Non-Veg Starter', name: 'Kodi Vepudu', veg: 'Veg' },
  { id: 204, section: 'Non-Veg Starter', name: 'Koli Kari Vada', veg: 'Veg' },
  { id: 205, section: 'Non-Veg Starter', name: 'Kung Pao Chicken', veg: 'Veg' },
  { id: 206, section: 'Non-Veg Starter', name: 'Kung Pao Fish', veg: 'Veg' },
  { id: 207, section: 'Non-Veg Starter', name: 'Lahoori Murgh Tikka', veg: 'Veg' },
  { id: 208, section: 'Non-Veg Starter', name: 'Lasooni Murgh Tikka', veg: 'Veg' },
  { id: 209, section: 'Non-Veg Starter', name: 'Lemon Chicken', veg: 'Veg' },
  { id: 210, section: 'Non-Veg Starter', name: 'Machli Amritsari', veg: 'Veg' },
  { id: 211, section: 'Non-Veg Starter', name: 'Machli Koliwada', veg: 'Veg' },
  { id: 212, section: 'Non-Veg Starter', name: 'Mahi Tikka', veg: 'Veg' },
  { id: 213, section: 'Non-Veg Starter', name: 'Meen Kari Vada', veg: 'Veg' },
  { id: 214, section: 'Non-Veg Starter', name: 'Meen Varuval', veg: 'Veg' },
  { id: 215, section: 'Non-Veg Starter', name: 'Murgh Achari Tikka', veg: 'Veg' },
  { id: 216, section: 'Non-Veg Starter', name: 'Murgh Gilafi Seekh', veg: 'Veg' },
  { id: 217, section: 'Non-Veg Starter', name: 'Murgh Hariyali Kebab', veg: 'Veg' },
  { id: 218, section: 'Non-Veg Starter', name: 'Murgh Ki Sooley', veg: 'Veg' },
  { id: 219, section: 'Non-Veg Starter', name: 'Murgh Malai Kebab', veg: 'Veg' },
  { id: 220, section: 'Non-Veg Starter', name: 'Murgh Malai Tikka', veg: 'Veg' },
  { id: 221, section: 'Non-Veg Starter', name: 'Murgh Shami Kebab', veg: 'Veg' },
  { id: 222, section: 'Non-Veg Starter', name: 'Murgh Tikka', veg: 'Veg' },
  { id: 223, section: 'Non-Veg Starter', name: 'Pepper Chicken', veg: 'Veg' },
  { id: 224, section: 'Non-Veg Starter', name: 'Peri Peri Chicken Poppers', veg: 'Veg' },
  { id: 225, section: 'Non-Veg Starter', name: 'Schezwan Chicken', veg: 'Veg' },
  { id: 226, section: 'Non-Veg Starter', name: 'Sweet And Sour Fish', veg: 'Veg' },
  { id: 227, section: 'Non-Veg Starter', name: 'Tawa Fried Curry Leaf Fish', veg: 'Veg' },
  { id: 228, section: 'Non-Veg Starter', name: 'Tawa Macchi', veg: 'Veg' },
  { id: 229, section: 'Non-Veg Starter', name: 'Tempura Fish', veg: 'Veg' },
  { id: 230, section: 'Non-Veg Starter', name: 'Thai Fish Cake', veg: 'Veg' },
  { id: 231, section: 'Non-Veg Starter', name: 'Velluli Kodi Vepudu', veg: 'Veg' },
  { id: 232, section: 'Salad', name: 'Aloo Chana Chat', veg: 'Veg' },
  { id: 233, section: 'Salad', name: 'Aloo Chat', veg: 'Veg' },
  { id: 234, section: 'Salad', name: 'Baby Corn And Bell Pepper Salad', veg: 'Veg' },
  { id: 235, section: 'Salad', name: 'Beans Tomato And Olive Salad', veg: 'Veg' },
  { id: 236, section: 'Salad', name: 'Channa Chat', veg: 'Veg' },
  { id: 237, section: 'Salad', name: 'Coleslaw Salad', veg: 'Veg' },
  { id: 238, section: 'Salad', name: 'Crispy Aloo Peanut Chat', veg: 'Veg' },
  { id: 239, section: 'Salad', name: 'Cucumber & Yogurt Salad', veg: 'Veg' },
  { id: 240, section: 'Salad', name: 'Cucumber And Yoghurt With Pomegranate Salad', veg: 'Veg' },
  { id: 241, section: 'Salad', name: 'Cucumber In Yoghurt', veg: 'Veg' },
  { id: 242, section: 'Salad', name: 'Dahi Bhalla', veg: 'Veg' },
  { id: 243, section: 'Salad', name: 'Dahi Papdi Chaat', veg: 'Veg' },
  { id: 244, section: 'Salad', name: 'Fruit Chat', veg: 'Veg' },
  { id: 245, section: 'Salad', name: 'German Potato Salad', veg: 'Veg' },
  { id: 246, section: 'Salad', name: 'Greek Salad With Feta', veg: 'Veg' },
  { id: 247, section: 'Salad', name: 'Green Salad', veg: 'Veg' },
  { id: 248, section: 'Salad', name: 'Grilled Aubergine & Lettuce With Feta Salad', veg: 'Veg' },
  { id: 249, section: 'Salad', name: 'Grilled Vegetables With Basil Pesto And Feta', veg: 'Veg' },
  { id: 250, section: 'Salad', name: 'Grilled Zucchini & Carrot With Mint Lemon Dressing', veg: 'Veg' },
  { id: 251, section: 'Salad', name: 'Kachumber Salad', veg: 'Veg' },
  { id: 252, section: 'Salad', name: 'Kasundi Mustard Potato With Garlic Jam', veg: 'Veg' },
  { id: 253, section: 'Salad', name: 'Kimchi Salad', veg: 'Veg' },
  { id: 254, section: 'Salad', name: 'Koshimbir Salad', veg: 'Veg' },
  { id: 255, section: 'Salad', name: 'Lachha Onion', veg: 'Veg' },
  { id: 256, section: 'Salad', name: 'Macaroni Peanut Salad', veg: 'Veg' },
  { id: 257, section: 'Salad', name: 'Mix Sprout Salad With Mint & Ginger Dressing', veg: 'Veg' },
  { id: 258, section: 'Salad', name: 'Mix Sprout With Vegetables', veg: 'Veg' },
  { id: 259, section: 'Salad', name: 'Mixed Sprouts', veg: 'Veg' },
  { id: 260, section: 'Salad', name: 'Papidi Discs Chat', veg: 'Veg' },
  { id: 261, section: 'Salad', name: 'Pasta Salad', veg: 'Veg' },
  { id: 262, section: 'Salad', name: 'Peanut Chat', veg: 'Veg' },
  { id: 263, section: 'Salad', name: 'Pickled Vegetables', veg: 'Veg' },
  { id: 264, section: 'Salad', name: 'Red Bean Lettuce With Tomato Salad', veg: 'Veg' },
  { id: 265, section: 'Salad', name: 'Russian Salad', veg: 'Veg' },
  { id: 266, section: 'Salad', name: 'Spicy Pineapple Chat', veg: 'Veg' },
  { id: 267, section: 'Salad', name: 'Sprout Salad', veg: 'Veg' },
  { id: 268, section: 'Salad', name: 'Sweet Corn & Veg Salad', veg: 'Veg' },
  { id: 269, section: 'Salad', name: 'Tadka Channa And Coconut Salad', veg: 'Veg' },
  { id: 270, section: 'Salad', name: 'Tandoor Salad', veg: 'Veg' },
  { id: 271, section: 'Salad', name: 'Thai Raw Papaya Salad', veg: 'Veg' },
  { id: 272, section: 'Salad', name: 'Thyme & Garlic Marinated Grilled Mushroom', veg: 'Veg' },
  { id: 273, section: 'Salad', name: 'Tomato & Basil Salad', veg: 'Veg' },
  { id: 274, section: 'Salad', name: 'Tossed Salad', veg: 'Veg' },
  { id: 275, section: 'Salad', name: 'Waldorf Salad', veg: 'Veg' },
  { id: 276, section: 'Veg Curry', name: 'Achari Baigan', veg: 'Veg' },
  { id: 277, section: 'Veg Curry', name: 'Achari Paneer Korma', veg: 'Veg' },
  { id: 278, section: 'Veg Curry', name: 'Aloo Capsicum Masala', veg: 'Veg' },
  { id: 279, section: 'Veg Curry', name: 'Aloo Cashew Iguru', veg: 'Veg' },
  { id: 280, section: 'Veg Curry', name: 'Aloo Fry', veg: 'Veg' },
  { id: 281, section: 'Veg Curry', name: 'Aloo Gobi Adraki', veg: 'Veg' },
  { id: 282, section: 'Veg Curry', name: 'Aloo Jeera', veg: 'Veg' },
  { id: 283, section: 'Veg Curry', name: 'Aloo Kurma', veg: 'Veg' },
  { id: 284, section: 'Veg Curry', name: 'Aloo Methi Fry', veg: 'Veg' },
  { id: 285, section: 'Veg Curry', name: 'Aloo Mutter Masala', veg: 'Veg' },
  { id: 286, section: 'Veg Curry', name: 'Aloo Mutter Vepudu', veg: 'Veg' },
  { id: 287, section: 'Veg Curry', name: 'Bagara Baigan', veg: 'Veg' },
  { id: 288, section: 'Veg Curry', name: 'Beans Poriyal', veg: 'Veg' },
  { id: 289, section: 'Veg Curry', name: 'Bhindi Amritsari', veg: 'Veg' },
  { id: 290, section: 'Veg Curry', name: 'Bhindi Cashew Fry', veg: 'Veg' },
  { id: 291, section: 'Veg Curry', name: 'Bhindi Do Pyaza', veg: 'Veg' },
  { id: 292, section: 'Veg Curry', name: 'Bhindi Fry', veg: 'Veg' },
  { id: 293, section: 'Veg Curry', name: 'Bhindi Kaju Peanut Fry', veg: 'Veg' },
  { id: 294, section: 'Veg Curry', name: 'Bhindi Peanut Fry', veg: 'Veg' },
  { id: 295, section: 'Veg Curry', name: 'Cabbage Pakodi', veg: 'Veg' },
  { id: 296, section: 'Veg Curry', name: 'Carrot Beans Fry', veg: 'Veg' },
  { id: 297, section: 'Veg Curry', name: 'Carrot Beans Poriyal', veg: 'Veg' },
  { id: 298, section: 'Veg Curry', name: 'Chili And Garlic Potato Wedge', veg: 'Veg' },
  { id: 299, section: 'Veg Curry', name: 'Dhingri Mutter Masala', veg: 'Veg' },
  { id: 300, section: 'Veg Curry', name: 'Donda Fry', veg: 'Veg' },
  { id: 301, section: 'Veg Curry', name: 'Donda Kaju Fry', veg: 'Veg' },
  { id: 302, section: 'Veg Curry', name: 'Dondakaya Fry', veg: 'Veg' },
  { id: 303, section: 'Veg Curry', name: 'Dondakaya Peanut Fry', veg: 'Veg' },
  { id: 304, section: 'Veg Curry', name: 'Dum Aloo', veg: 'Veg' },
  { id: 305, section: 'Veg Curry', name: 'Dum Aloo Banarasi', veg: 'Veg' },
  { id: 306, section: 'Veg Curry', name: 'Dum Aloo Kashmiri', veg: 'Veg' },
  { id: 307, section: 'Veg Curry', name: 'Gatta Kadhi', veg: 'Veg' },
  { id: 308, section: 'Veg Curry', name: 'Gobi 65 Fry', veg: 'Veg' },
  { id: 309, section: 'Veg Curry', name: 'Gobi Capsicum Masala Curry', veg: 'Veg' },
  { id: 310, section: 'Veg Curry', name: 'Gobi Musallam', veg: 'Veg' },
  { id: 311, section: 'Veg Curry', name: 'Gujarati Kadhi', veg: 'Veg' },
  { id: 312, section: 'Veg Curry', name: 'Guthi Vankaya', veg: 'Veg' },
  { id: 313, section: 'Veg Curry', name: 'Guttivankaya', veg: 'Veg' },
  { id: 314, section: 'Veg Curry', name: 'Jacket Potato', veg: 'Veg' },
  { id: 315, section: 'Veg Curry', name: 'Jaituni Paneer Masala', veg: 'Veg' },
  { id: 316, section: 'Veg Curry', name: 'Kadai Paneer', veg: 'Veg' },
  { id: 317, section: 'Veg Curry', name: 'Kadai Vegetable', veg: 'Veg' },
  { id: 318, section: 'Veg Curry', name: 'Kadi Pakodi', veg: 'Veg' },
  { id: 319, section: 'Veg Curry', name: 'Kalegura Telumpu', veg: 'Veg' },
  { id: 320, section: 'Veg Curry', name: 'Kanda Turumu', veg: 'Veg' },
  { id: 321, section: 'Veg Curry', name: 'Lasooni Palak', veg: 'Veg' },
  { id: 322, section: 'Veg Curry', name: 'Lasooni Palak Paneer', veg: 'Veg' },
  { id: 323, section: 'Veg Curry', name: 'Makai Paneer Makhana', veg: 'Veg' },
  { id: 324, section: 'Veg Curry', name: 'Malai Kofta', veg: 'Veg' },
  { id: 325, section: 'Veg Curry', name: 'Malai Kofta Curry', veg: 'Veg' },
  { id: 326, section: 'Veg Curry', name: 'Malai Paneer Kofta', veg: 'Veg' },
  { id: 327, section: 'Veg Curry', name: 'Mashed Potato', veg: 'Veg' },
  { id: 328, section: 'Veg Curry', name: 'Methi Chaman', veg: 'Veg' },
  { id: 329, section: 'Veg Curry', name: 'Mix Veg Korma', veg: 'Veg' },
  { id: 330, section: 'Veg Curry', name: 'Mixed Veg Curry', veg: 'Veg' },
  { id: 331, section: 'Veg Curry', name: 'Mixed Veg Fry', veg: 'Veg' },
  { id: 332, section: 'Veg Curry', name: 'Mixed Vegetable Korma', veg: 'Veg' },
  { id: 333, section: 'Veg Curry', name: 'Moroccan Spice Oven Roasted Potato', veg: 'Veg' },
  { id: 334, section: 'Veg Curry', name: 'Mutter Paneer', veg: 'Veg' },
  { id: 335, section: 'Veg Curry', name: 'Mutter Paneer Pulao Gravy', veg: 'Veg' },
  { id: 336, section: 'Veg Curry', name: 'Navratan Korma', veg: 'Veg' },
  { id: 337, section: 'Veg Curry', name: 'Nizami Handi', veg: 'Veg' },
  { id: 338, section: 'Veg Curry', name: 'Palak Kofta Curry', veg: 'Veg' },
  { id: 339, section: 'Veg Curry', name: 'Palak Makai Makhana', veg: 'Veg' },
  { id: 340, section: 'Veg Curry', name: 'Palak Paneer', veg: 'Veg' },
  { id: 341, section: 'Veg Curry', name: 'Paneer Awadhi Korma', veg: 'Veg' },
  { id: 342, section: 'Veg Curry', name: 'Paneer Bhurji', veg: 'Veg' },
  { id: 343, section: 'Veg Curry', name: 'Paneer Butter Masala', veg: 'Veg' },
  { id: 344, section: 'Veg Curry', name: 'Paneer Do Pyaza', veg: 'Veg' },
  { id: 345, section: 'Veg Curry', name: 'Paneer Hara Pyaz', veg: 'Veg' },
  { id: 346, section: 'Veg Curry', name: 'Paneer Jalfrezi', veg: 'Veg' },
  { id: 347, section: 'Veg Curry', name: 'Paneer Kali Mirch', veg: 'Veg' },
  { id: 348, section: 'Veg Curry', name: 'Paneer Khajur Ke Kofta Curry', veg: 'Veg' },
  { id: 349, section: 'Veg Curry', name: 'Paneer Khatta Pyaz', veg: 'Veg' },
  { id: 350, section: 'Veg Curry', name: 'Paneer Khoya Masala', veg: 'Veg' },
  { id: 351, section: 'Veg Curry', name: 'Paneer Khurchan', veg: 'Veg' },
  { id: 352, section: 'Veg Curry', name: 'Paneer Korma', veg: 'Veg' },
  { id: 353, section: 'Veg Curry', name: 'Paneer Kumb Masala', veg: 'Veg' },
  { id: 354, section: 'Veg Curry', name: 'Paneer Laal Mirch Masala', veg: 'Veg' },
  { id: 355, section: 'Veg Curry', name: 'Paneer Lababdar', veg: 'Veg' },
  { id: 356, section: 'Veg Curry', name: 'Paneer Long Latta', veg: 'Veg' },
  { id: 357, section: 'Veg Curry', name: 'Paneer Makhani', veg: 'Veg' },
  { id: 358, section: 'Veg Curry', name: 'Paneer Makhanwala', veg: 'Veg' },
  { id: 359, section: 'Veg Curry', name: 'Paneer Mutter Korma', veg: 'Veg' },
  { id: 360, section: 'Veg Curry', name: 'Paneer Pasanda', veg: 'Veg' },
  { id: 361, section: 'Veg Curry', name: 'Paneer Shahi Korma', veg: 'Veg' },
  { id: 362, section: 'Veg Curry', name: 'Paneer Shimla Mirch', veg: 'Veg' },
  { id: 363, section: 'Veg Curry', name: 'Paneer Tikka Masala', veg: 'Veg' },
  { id: 364, section: 'Veg Curry', name: 'Papad Paneer', veg: 'Veg' },
  { id: 365, section: 'Veg Curry', name: 'Paprika Spiced Potato Wedges', veg: 'Veg' },
  { id: 366, section: 'Veg Curry', name: 'Potato Lyonnais', veg: 'Veg' },
  { id: 367, section: 'Veg Curry', name: 'Punjabi Kadhi Pakora', veg: 'Veg' },
  { id: 368, section: 'Veg Curry', name: 'Rajwada Paneer', veg: 'Veg' },
  { id: 369, section: 'Veg Curry', name: 'Saag Paneer', veg: 'Veg' },
  { id: 370, section: 'Veg Curry', name: 'Shahi Paneer', veg: 'Veg' },
  { id: 371, section: 'Veg Curry', name: 'Sindhi Kadhi', veg: 'Veg' },
  { id: 372, section: 'Veg Curry', name: 'Subz Diwani Handi', veg: 'Veg' },
  { id: 373, section: 'Veg Curry', name: 'Subz Kofta In Saag', veg: 'Veg' },
  { id: 374, section: 'Veg Curry', name: 'Subz Kolhapuri', veg: 'Veg' },
  { id: 375, section: 'Veg Curry', name: 'Subz Makhanwala', veg: 'Veg' },
  { id: 376, section: 'Veg Curry', name: 'Subz Meloni', veg: 'Veg' },
  { id: 377, section: 'Veg Curry', name: 'Subz Shahi Korma', veg: 'Veg' },
  { id: 378, section: 'Veg Curry', name: 'Tawa Subz', veg: 'Veg' },
  { id: 379, section: 'Veg Curry', name: 'Teen Mirch Ka Paneer Korma', veg: 'Veg' },
  { id: 380, section: 'Veg Curry', name: 'Thotakura Fry', veg: 'Veg' },
  { id: 381, section: 'Veg Curry', name: 'Vankaya Pakodi', veg: 'Veg' },
  { id: 382, section: 'Veg Curry', name: 'Veg Korma', veg: 'Veg' },
  { id: 383, section: 'Veg Curry', name: 'Vegetable Chettinad', veg: 'Veg' },
  { id: 384, section: 'Veg Curry', name: 'Vegetable Jalfrezi', veg: 'Veg' },
  { id: 385, section: 'Dal', name: 'Amritsari Cholley', veg: 'Veg' },
  { id: 386, section: 'Dal', name: 'Dal Amritsari', veg: 'Veg' },
  { id: 387, section: 'Dal', name: 'Dal Makhani', veg: 'Veg' },
  { id: 388, section: 'Dal', name: 'Dal Meloni', veg: 'Veg' },
  { id: 389, section: 'Dal', name: 'Dal Palak Tadka', veg: 'Veg' },
  { id: 390, section: 'Dal', name: 'Dal Panchmel', veg: 'Veg' },
  { id: 391, section: 'Dal', name: 'Dal Tadka', veg: 'Veg' },
  { id: 392, section: 'Dal', name: 'Dosakaya Pappu', veg: 'Veg' },
  { id: 393, section: 'Dal', name: 'Gongura Pappu', veg: 'Veg' },
  { id: 394, section: 'Dal', name: 'Hing Dal Tadka', veg: 'Veg' },
  { id: 395, section: 'Dal', name: 'Hyderabadi Khatti Dal', veg: 'Veg' },
  { id: 396, section: 'Dal', name: 'Lasooni Dal', veg: 'Veg' },
  { id: 397, section: 'Dal', name: 'Lasooni Dal Tadka', veg: 'Veg' },
  { id: 398, section: 'Dal', name: 'Mamidikaya Pappu', veg: 'Veg' },
  { id: 399, section: 'Dal', name: 'Mango Dal', veg: 'Veg' },
  { id: 400, section: 'Dal', name: 'Mango Dal (Seasonal)', veg: 'Veg' },
  { id: 401, section: 'Dal', name: 'Menthikura Pappu', veg: 'Veg' },
  { id: 402, section: 'Dal', name: 'Methi Dal', veg: 'Veg' },
  { id: 403, section: 'Dal', name: 'Moong Dal Masala', veg: 'Veg' },
  { id: 404, section: 'Dal', name: 'Mudda Pappu', veg: 'Veg' },
  { id: 405, section: 'Dal', name: 'Palak Dal', veg: 'Veg' },
  { id: 406, section: 'Dal', name: 'Palakura Pappu', veg: 'Veg' },
  { id: 407, section: 'Dal', name: 'Pancharatan Dal', veg: 'Veg' },
  { id: 408, section: 'Dal', name: 'Rajma Masala', veg: 'Veg' },
  { id: 409, section: 'Dal', name: 'Rajma Rasilla', veg: 'Veg' },
  { id: 410, section: 'Dal', name: 'Thotakura Pesara Pappu', veg: 'Veg' },
  { id: 411, section: 'Dal', name: 'Tomato Dal', veg: 'Veg' },
  { id: 412, section: 'Dal', name: 'Tomato Pappu', veg: 'Veg' },
  { id: 413, section: 'Dal', name: 'Yellow Dal Tadka', veg: 'Veg' },
  { id: 414, section: 'Veg Rice / Biryani / Pulao', name: 'Andhra Veg Pulao', veg: 'Veg' },
  { id: 415, section: 'Veg Rice / Biryani / Pulao', name: 'Bagara Rice', veg: 'Veg' },
  { id: 416, section: 'Veg Rice / Biryani / Pulao', name: 'Bhuna Pyaz Ka Pulao', veg: 'Veg' },
  { id: 417, section: 'Veg Rice / Biryani / Pulao', name: 'Brinji Pulao', veg: 'Veg' },
  { id: 418, section: 'Veg Rice / Biryani / Pulao', name: 'Burnt Garlic Fried Rice', veg: 'Veg' },
  { id: 419, section: 'Veg Rice / Biryani / Pulao', name: 'Chili Garlic Noodles', veg: 'Veg' },
  { id: 420, section: 'Veg Rice / Biryani / Pulao', name: 'Coconut Rice', veg: 'Veg' },
  { id: 421, section: 'Veg Rice / Biryani / Pulao', name: 'Coriander Rice', veg: 'Veg' },
  { id: 422, section: 'Veg Rice / Biryani / Pulao', name: 'Curd Rice', veg: 'Veg' },
  { id: 423, section: 'Veg Rice / Biryani / Pulao', name: 'Ghee Bhat', veg: 'Veg' },
  { id: 424, section: 'Veg Rice / Biryani / Pulao', name: 'Ginger And Basil Noodles', veg: 'Veg' },
  { id: 425, section: 'Veg Rice / Biryani / Pulao', name: 'Gongura Rice', veg: 'Veg' },
  { id: 426, section: 'Veg Rice / Biryani / Pulao', name: 'Green Peas Pulao', veg: 'Veg' },
  { id: 427, section: 'Veg Rice / Biryani / Pulao', name: 'Hyderabadi Kitchidi', veg: 'Veg' },
  { id: 428, section: 'Veg Rice / Biryani / Pulao', name: 'Jeera Makai Pulao', veg: 'Veg' },
  { id: 429, section: 'Veg Rice / Biryani / Pulao', name: 'Jeera Pulao', veg: 'Veg' },
  { id: 430, section: 'Veg Rice / Biryani / Pulao', name: 'Jeera Rice', veg: 'Veg' },
  { id: 431, section: 'Veg Rice / Biryani / Pulao', name: 'Kabuli Chane Ka Pulao', veg: 'Veg' },
  { id: 432, section: 'Veg Rice / Biryani / Pulao', name: 'Kabuli Pulao', veg: 'Veg' },
  { id: 433, section: 'Veg Rice / Biryani / Pulao', name: 'Kaju Peas Pulao', veg: 'Veg' },
  { id: 434, section: 'Veg Rice / Biryani / Pulao', name: 'Kaju Pyaz Pulao', veg: 'Veg' },
  { id: 435, section: 'Veg Rice / Biryani / Pulao', name: 'Karivepaku Rice', veg: 'Veg' },
  { id: 436, section: 'Veg Rice / Biryani / Pulao', name: 'Kashmiri Pulao', veg: 'Veg' },
  { id: 437, section: 'Veg Rice / Biryani / Pulao', name: 'Kundu Saddam (Garlic Rice)', veg: 'Veg' },
  { id: 438, section: 'Veg Rice / Biryani / Pulao', name: 'Lemon Rice', veg: 'Veg' },
  { id: 439, section: 'Veg Rice / Biryani / Pulao', name: 'Mutter Paneer Pulao', veg: 'Veg' },
  { id: 440, section: 'Veg Rice / Biryani / Pulao', name: 'Mutter Pulao', veg: 'Veg' },
  { id: 441, section: 'Veg Rice / Biryani / Pulao', name: 'Navratan Pulao', veg: 'Veg' },
  { id: 442, section: 'Veg Rice / Biryani / Pulao', name: 'Panasakaya Biryani', veg: 'Veg' },
  { id: 443, section: 'Veg Rice / Biryani / Pulao', name: 'Pudina Rice', veg: 'Veg' },
  { id: 444, section: 'Veg Rice / Biryani / Pulao', name: 'Pulihora', veg: 'Veg' },
  { id: 445, section: 'Veg Rice / Biryani / Pulao', name: 'Singapore Veg Noodles', veg: 'Veg' },
  { id: 446, section: 'Veg Rice / Biryani / Pulao', name: 'Singapore Vegetable Fried Rice', veg: 'Veg' },
  { id: 447, section: 'Veg Rice / Biryani / Pulao', name: 'Spinach And Garlic Noodles', veg: 'Veg' },
  { id: 448, section: 'Veg Rice / Biryani / Pulao', name: 'Subz Dum Pulao', veg: 'Veg' },
  { id: 449, section: 'Veg Rice / Biryani / Pulao', name: 'Subz Ki Tehri', veg: 'Veg' },
  { id: 450, section: 'Veg Rice / Biryani / Pulao', name: 'Szechuan Fried Rice', veg: 'Veg' },
  { id: 451, section: 'Veg Rice / Biryani / Pulao', name: 'Szechuan Noodles', veg: 'Veg' },
  { id: 452, section: 'Veg Rice / Biryani / Pulao', name: 'Tamarind Rice', veg: 'Veg' },
  { id: 453, section: 'Veg Rice / Biryani / Pulao', name: 'Tomato Basil Noodles', veg: 'Veg' },
  { id: 454, section: 'Veg Rice / Biryani / Pulao', name: 'Tomato Rice', veg: 'Veg' },
  { id: 455, section: 'Veg Rice / Biryani / Pulao', name: 'Ulavacharu Biryani', veg: 'Veg' },
  { id: 456, section: 'Veg Rice / Biryani / Pulao', name: 'Veg Biryani', veg: 'Veg' },
  { id: 457, section: 'Veg Rice / Biryani / Pulao', name: 'Veg Dum Biryani', veg: 'Veg' },
  { id: 458, section: 'Veg Rice / Biryani / Pulao', name: 'Veg Manchurian Noodles', veg: 'Veg' },
  { id: 459, section: 'Veg Rice / Biryani / Pulao', name: 'Veg Pulao', veg: 'Veg' },
  { id: 460, section: 'Veg Rice / Biryani / Pulao', name: 'Vegetable Dum Biryani', veg: 'Veg' },
  { id: 461, section: 'Veg Rice / Biryani / Pulao', name: 'Vegetable Fried Rice', veg: 'Veg' },
  { id: 462, section: 'Veg Rice / Biryani / Pulao', name: 'Vegetable Pulao', veg: 'Veg' },
  { id: 463, section: 'Non-Veg Biryani', name: 'Andhra Chicken Pulao', veg: 'Veg' },
  { id: 464, section: 'Non-Veg Biryani', name: 'Biryani Chicken Pulao', veg: 'Veg' },
  { id: 465, section: 'Non-Veg Biryani', name: 'Bombay Fish Biryani', veg: 'Veg' },
  { id: 466, section: 'Non-Veg Biryani', name: 'Chicken 65 Biryani', veg: 'Veg' },
  { id: 467, section: 'Non-Veg Biryani', name: 'Chicken Biryani', veg: 'Veg' },
  { id: 468, section: 'Non-Veg Biryani', name: 'Chicken Dum Biryani', veg: 'Veg' },
  { id: 469, section: 'Non-Veg Biryani', name: 'Chicken Fry Piece Biryani', veg: 'Veg' },
  { id: 470, section: 'Non-Veg Biryani', name: 'Chicken Sufyani Biryani', veg: 'Veg' },
  { id: 471, section: 'Non-Veg Biryani', name: 'Chicken Zafrani Biryani', veg: 'Veg' },
  { id: 472, section: 'Non-Veg Biryani', name: 'Chitti Muthyalu Prawns Pulao', veg: 'Veg' },
  { id: 473, section: 'Non-Veg Biryani', name: 'Dum Ka Mutton Biryani', veg: 'Veg' },
  { id: 474, section: 'Non-Veg Biryani', name: 'Gongura Mutton Pulao', veg: 'Veg' },
  { id: 475, section: 'Non-Veg Biryani', name: 'Hyderabadi Chicken Dum Biryani', veg: 'Veg' },
  { id: 476, section: 'Non-Veg Biryani', name: 'Hyderabadi Murgh Dum Biryani', veg: 'Veg' },
  { id: 477, section: 'Non-Veg Biryani', name: 'Hyderabadi Mutton Biryani', veg: 'Veg' },
  { id: 478, section: 'Non-Veg Biryani', name: 'Kheema Biryani', veg: 'Veg' },
  { id: 479, section: 'Non-Veg Biryani', name: 'Mutton Biryani', veg: 'Veg' },
  { id: 480, section: 'Non-Veg Biryani', name: 'Mutton Dum Biryani', veg: 'Veg' },
  { id: 481, section: 'Non-Veg Biryani', name: 'Rajugari Kodi Pulao', veg: 'Veg' },
  { id: 482, section: 'Non-Veg Biryani', name: 'Sufyani Biryani', veg: 'Veg' },
  { id: 483, section: 'Non-Veg Biryani', name: 'Ulavacharu Chicken Biryani', veg: 'Veg' },
  { id: 484, section: 'Non-Veg Biryani', name: 'Zafrani Biryani', veg: 'Veg' },
  { id: 485, section: 'Non-Veg Curry', name: 'Achari Chicken', veg: 'Veg' },
  { id: 486, section: 'Non-Veg Curry', name: 'Achari Machhi', veg: 'Veg' },
  { id: 487, section: 'Non-Veg Curry', name: 'Achari Murgh', veg: 'Veg' },
  { id: 488, section: 'Non-Veg Curry', name: 'Amritsari Machhi Masala', veg: 'Veg' },
  { id: 489, section: 'Non-Veg Curry', name: 'Andhra Chicken Curry', veg: 'Veg' },
  { id: 490, section: 'Non-Veg Curry', name: 'Andhra Mutton', veg: 'Veg' },
  { id: 491, section: 'Non-Veg Curry', name: 'Andhra Mutton Curry', veg: 'Veg' },
  { id: 492, section: 'Non-Veg Curry', name: 'Andhra Style Fish Curry', veg: 'Veg' },
  { id: 493, section: 'Non-Veg Curry', name: 'Awadhi Murgh Korma', veg: 'Veg' },
  { id: 494, section: 'Non-Veg Curry', name: 'Baked Fish', veg: 'Veg' },
  { id: 495, section: 'Non-Veg Curry', name: 'Bengali Fish Curry', veg: 'Veg' },
  { id: 496, section: 'Non-Veg Curry', name: 'Bhuna Gosht', veg: 'Veg' },
  { id: 497, section: 'Non-Veg Curry', name: 'Bhuna Murgh', veg: 'Veg' },
  { id: 498, section: 'Non-Veg Curry', name: 'Bikaneri Murgh Hara Pyaz', veg: 'Veg' },
  { id: 499, section: 'Non-Veg Curry', name: 'Bommidala Pulusu', veg: 'Veg' },
  { id: 500, section: 'Non-Veg Curry', name: 'Boneless Fish Fry', veg: 'Veg' },
  { id: 501, section: 'Non-Veg Curry', name: 'Braised Lamb With Three Beans', veg: 'Veg' },
  { id: 502, section: 'Non-Veg Curry', name: 'Butter Chicken', veg: 'Veg' },
  { id: 503, section: 'Non-Veg Curry', name: 'Casserole Of Lamb With Tomato And Herbs', veg: 'Veg' },
  { id: 504, section: 'Non-Veg Curry', name: 'Chapala Pulusu', veg: 'Veg' },
  { id: 505, section: 'Non-Veg Curry', name: 'Chicken Chettinad', veg: 'Veg' },
  { id: 506, section: 'Non-Veg Curry', name: 'Chicken Curry', veg: 'Veg' },
  { id: 507, section: 'Non-Veg Curry', name: 'Chicken Fry', veg: 'Veg' },
  { id: 508, section: 'Non-Veg Curry', name: 'Chicken In Black Bean', veg: 'Veg' },
  { id: 509, section: 'Non-Veg Curry', name: 'Chicken In Chilli Basil', veg: 'Veg' },
  { id: 510, section: 'Non-Veg Curry', name: 'Chicken In Chilli Bean Hunan', veg: 'Veg' },
  { id: 511, section: 'Non-Veg Curry', name: 'Chicken In Honey Chilli Manchurian', veg: 'Veg' },
  { id: 512, section: 'Non-Veg Curry', name: 'Chicken In Hot Garlic', veg: 'Veg' },
  { id: 513, section: 'Non-Veg Curry', name: 'Chicken In Oyster Garlic', veg: 'Veg' },
  { id: 514, section: 'Non-Veg Curry', name: 'Chicken In Schezwan', veg: 'Veg' },
  { id: 515, section: 'Non-Veg Curry', name: 'Chicken In Sweet & Sour', veg: 'Veg' },
  { id: 516, section: 'Non-Veg Curry', name: 'Chicken Korma', veg: 'Veg' },
  { id: 517, section: 'Non-Veg Curry', name: 'Chicken Massaman Curry', veg: 'Veg' },
  { id: 518, section: 'Non-Veg Curry', name: 'Chicken Roghani', veg: 'Veg' },
  { id: 519, section: 'Non-Veg Curry', name: 'Chicken Shahi', veg: 'Veg' },
  { id: 520, section: 'Non-Veg Curry', name: 'Chicken Thai Curry (Red/Green/Yellow)', veg: 'Veg' },
  { id: 521, section: 'Non-Veg Curry', name: 'Chicken Tikka Masala', veg: 'Veg' },
  { id: 522, section: 'Non-Veg Curry', name: 'Dosakai Mamsam', veg: 'Veg' },
  { id: 523, section: 'Non-Veg Curry', name: 'Dum Ka Chicken', veg: 'Veg' },
  { id: 524, section: 'Non-Veg Curry', name: 'Dum Ka Murgh', veg: 'Veg' },
  { id: 525, section: 'Non-Veg Curry', name: 'Egg Curry', veg: 'Veg' },
  { id: 526, section: 'Non-Veg Curry', name: 'Egg Fry', veg: 'Veg' },
  { id: 527, section: 'Non-Veg Curry', name: 'Egg Masala', veg: 'Veg' },
  { id: 528, section: 'Non-Veg Curry', name: 'Fillet De Fish Almondine', veg: 'Veg' },
  { id: 529, section: 'Non-Veg Curry', name: 'Fillet Fish Bonne Femme', veg: 'Veg' },
  { id: 530, section: 'Non-Veg Curry', name: 'Fish Belle Meuniere', veg: 'Veg' },
  { id: 531, section: 'Non-Veg Curry', name: 'Fish Curry', veg: 'Veg' },
  { id: 532, section: 'Non-Veg Curry', name: 'Fish In Black Bean', veg: 'Veg' },
  { id: 533, section: 'Non-Veg Curry', name: 'Fish In Chili Basil', veg: 'Veg' },
  { id: 534, section: 'Non-Veg Curry', name: 'Fish In Chili Bean Hunan', veg: 'Veg' },
  { id: 535, section: 'Non-Veg Curry', name: 'Fish In Honey Chili Manchurian', veg: 'Veg' },
  { id: 536, section: 'Non-Veg Curry', name: 'Fish In Hot Garlic', veg: 'Veg' },
  { id: 537, section: 'Non-Veg Curry', name: 'Fish In Massaman Curry', veg: 'Veg' },
  { id: 538, section: 'Non-Veg Curry', name: 'Fish In Oyster Garlic', veg: 'Veg' },
  { id: 539, section: 'Non-Veg Curry', name: 'Fish In Sweet N Sour', veg: 'Veg' },
  { id: 540, section: 'Non-Veg Curry', name: 'Fish In Szechuan', veg: 'Veg' },
  { id: 541, section: 'Non-Veg Curry', name: 'Fish Masala Curry', veg: 'Veg' },
  { id: 542, section: 'Non-Veg Curry', name: 'Fish Orly', veg: 'Veg' },
  { id: 543, section: 'Non-Veg Curry', name: 'Fish Pulusu', veg: 'Veg' },
  { id: 544, section: 'Non-Veg Curry', name: 'Fish Thai Curry (Red/Green/Yellow)', veg: 'Veg' },
  { id: 545, section: 'Non-Veg Curry', name: 'Fried Fish With Tartare Sauce', veg: 'Veg' },
  { id: 546, section: 'Non-Veg Curry', name: 'Garlic Chicken', veg: 'Veg' },
  { id: 547, section: 'Non-Veg Curry', name: 'Ginger Chicken', veg: 'Veg' },
  { id: 548, section: 'Non-Veg Curry', name: 'Ginger Prawn', veg: 'Veg' },
  { id: 549, section: 'Non-Veg Curry', name: 'Goan Fish Curry', veg: 'Veg' },
  { id: 550, section: 'Non-Veg Curry', name: 'Golden Fried Prawns', veg: 'Veg' },
  { id: 551, section: 'Non-Veg Curry', name: 'Gongura Chicken', veg: 'Veg' },
  { id: 552, section: 'Non-Veg Curry', name: 'Gongura Mamsam', veg: 'Veg' },
  { id: 553, section: 'Non-Veg Curry', name: 'Gongura Mutton', veg: 'Veg' },
  { id: 554, section: 'Non-Veg Curry', name: 'Gosht Hari Mirch', veg: 'Veg' },
  { id: 555, section: 'Non-Veg Curry', name: 'Gosht Saagwala', veg: 'Veg' },
  { id: 556, section: 'Non-Veg Curry', name: 'Grilled Fish With Caper Sauce', veg: 'Veg' },
  { id: 557, section: 'Non-Veg Curry', name: 'Grilled Fish With Pineapple And Salsa', veg: 'Veg' },
  { id: 558, section: 'Non-Veg Curry', name: 'Grilled Fish With Ratatouille', veg: 'Veg' },
  { id: 559, section: 'Non-Veg Curry', name: 'Guntur Kodi Kura', veg: 'Veg' },
  { id: 560, section: 'Non-Veg Curry', name: 'Herb Crusted Fish With Basil Lemon Butter Sauce', veg: 'Veg' },
  { id: 561, section: 'Non-Veg Curry', name: 'Herb Poached Fish With Garden Greens', veg: 'Veg' },
  { id: 562, section: 'Non-Veg Curry', name: 'Home Style Fish Curry', veg: 'Veg' },
  { id: 563, section: 'Non-Veg Curry', name: 'Hungarian Lamb Stew', veg: 'Veg' },
  { id: 564, section: 'Non-Veg Curry', name: 'Hyderabadi Home Style Chicken Curry', veg: 'Veg' },
  { id: 565, section: 'Non-Veg Curry', name: 'Irish Lamb Stew With Potato And Onion', veg: 'Veg' },
  { id: 566, section: 'Non-Veg Curry', name: 'Kadai Chicken', veg: 'Veg' },
  { id: 567, section: 'Non-Veg Curry', name: 'Kadai Murgh', veg: 'Veg' },
  { id: 568, section: 'Non-Veg Curry', name: 'Karla Style Fish Curry', veg: 'Veg' },
  { id: 569, section: 'Non-Veg Curry', name: 'Kodi Kura', veg: 'Veg' },
  { id: 570, section: 'Non-Veg Curry', name: 'Laal Maas', veg: 'Veg' },
  { id: 571, section: 'Non-Veg Curry', name: 'Lagan Chicken', veg: 'Veg' },
  { id: 572, section: 'Non-Veg Curry', name: 'Lamb Moussaka', veg: 'Veg' },
  { id: 573, section: 'Non-Veg Curry', name: 'Lamb Ragout', veg: 'Veg' },
  { id: 574, section: 'Non-Veg Curry', name: 'Macher Jhol', veg: 'Veg' },
  { id: 575, section: 'Non-Veg Curry', name: 'Machli Ka Salan', veg: 'Veg' },
  { id: 576, section: 'Non-Veg Curry', name: 'Machli Masala', veg: 'Veg' },
  { id: 577, section: 'Non-Veg Curry', name: 'Madras Meen Kulambu', veg: 'Veg' },
  { id: 578, section: 'Non-Veg Curry', name: 'Mahi Kaliyan', veg: 'Veg' },
  { id: 579, section: 'Non-Veg Curry', name: 'Malabar Fish Curry', veg: 'Veg' },
  { id: 580, section: 'Non-Veg Curry', name: 'Mangalore Fish Curry', veg: 'Veg' },
  { id: 581, section: 'Non-Veg Curry', name: 'Meen Moilee', veg: 'Veg' },
  { id: 582, section: 'Non-Veg Curry', name: 'Methi Chicken', veg: 'Veg' },
  { id: 583, section: 'Non-Veg Curry', name: 'Methi Fish', veg: 'Veg' },
  { id: 584, section: 'Non-Veg Curry', name: 'Methi Murgh', veg: 'Veg' },
  { id: 585, section: 'Non-Veg Curry', name: 'Methi Mutton', veg: 'Veg' },
  { id: 586, section: 'Non-Veg Curry', name: 'Murgh Do Pyaza', veg: 'Veg' },
  { id: 587, section: 'Non-Veg Curry', name: 'Murgh Kali Mirch', veg: 'Veg' },
  { id: 588, section: 'Non-Veg Curry', name: 'Murgh Khurchan', veg: 'Veg' },
  { id: 589, section: 'Non-Veg Curry', name: 'Murgh Lababdar', veg: 'Veg' },
  { id: 590, section: 'Non-Veg Curry', name: 'Murgh Makhani', veg: 'Veg' },
  { id: 591, section: 'Non-Veg Curry', name: 'Murgh Masala', veg: 'Veg' },
  { id: 592, section: 'Non-Veg Curry', name: 'Murgh Saag Wala', veg: 'Veg' },
  { id: 593, section: 'Non-Veg Curry', name: 'Murgh Shahi Korma', veg: 'Veg' },
  { id: 594, section: 'Non-Veg Curry', name: 'Mutton Kali Mirch', veg: 'Veg' },
  { id: 595, section: 'Non-Veg Curry', name: 'Mutton Keema Curry', veg: 'Veg' },
  { id: 596, section: 'Non-Veg Curry', name: 'Mutton Kolhapuri', veg: 'Veg' },
  { id: 597, section: 'Non-Veg Curry', name: 'Mutton Korma', veg: 'Veg' },
  { id: 598, section: 'Non-Veg Curry', name: 'Mutton Marag', veg: 'Veg' },
  { id: 599, section: 'Non-Veg Curry', name: 'Mutton Masala', veg: 'Veg' },
  { id: 600, section: 'Non-Veg Curry', name: 'Mutton Rogan Josh', veg: 'Veg' },
  { id: 601, section: 'Non-Veg Curry', name: 'Nawabi Murgh', veg: 'Veg' },
  { id: 602, section: 'Non-Veg Curry', name: 'Nellore Chapala Pulusu', veg: 'Veg' },
  { id: 603, section: 'Non-Veg Curry', name: 'Nilgiri Fish Curry', veg: 'Veg' },
  { id: 604, section: 'Non-Veg Curry', name: 'Pan Fried Fish In Caper Butter', veg: 'Veg' },
  { id: 605, section: 'Non-Veg Curry', name: 'Pan Fried Fish With Verde Sauce', veg: 'Veg' },
  { id: 606, section: 'Non-Veg Curry', name: 'Prawns Pulusu', veg: 'Veg' },
  { id: 607, section: 'Non-Veg Curry', name: 'Punjabi Murgh', veg: 'Veg' },
  { id: 608, section: 'Non-Veg Curry', name: 'Rara Murgh', veg: 'Veg' },
  { id: 609, section: 'Non-Veg Curry', name: 'Rarha Gosht', veg: 'Veg' },
  { id: 610, section: 'Non-Veg Curry', name: 'Roast Chicken', veg: 'Veg' },
  { id: 611, section: 'Non-Veg Curry', name: 'Roast Chicken Gravy', veg: 'Veg' },
  { id: 612, section: 'Non-Veg Curry', name: 'Saag Murgh', veg: 'Veg' },
  { id: 613, section: 'Non-Veg Curry', name: 'Seafood Bouillabaisse', veg: 'Veg' },
  { id: 614, section: 'Non-Veg Curry', name: 'Shahi Chicken', veg: 'Veg' },
  { id: 615, section: 'Non-Veg Curry', name: 'Special Fish Curry', veg: 'Veg' },
  { id: 616, section: 'Non-Veg Curry', name: 'Tamatar Main Machli', veg: 'Veg' },
  { id: 617, section: 'Non-Veg Curry', name: 'Telangana Chapa Kura', veg: 'Veg' },
  { id: 618, section: 'Non-Veg Curry', name: 'Telangana Chicken', veg: 'Veg' },
  { id: 619, section: 'Non-Veg Curry', name: 'Telangana Style Kodi Kura', veg: 'Veg' },
  { id: 620, section: 'Non-Veg Curry', name: 'Zafrani Murgh Korma', veg: 'Veg' },
  { id: 621, section: 'Indian Bread', name: 'Butter Naan', veg: 'Veg' },
  { id: 622, section: 'Indian Bread', name: 'Chapati', veg: 'Veg' },
  { id: 623, section: 'Indian Bread', name: 'Kulcha', veg: 'Veg' },
  { id: 624, section: 'Indian Bread', name: 'Lachha Paratha', veg: 'Veg' },
  { id: 625, section: 'Indian Bread', name: 'Masala Poori', veg: 'Veg' },
  { id: 626, section: 'Indian Bread', name: 'Methi Paratha', veg: 'Veg' },
  { id: 627, section: 'Indian Bread', name: 'Missi Roti', veg: 'Veg' },
  { id: 628, section: 'Indian Bread', name: 'Naan', veg: 'Veg' },
  { id: 629, section: 'Indian Bread', name: 'Palak Poori', veg: 'Veg' },
  { id: 630, section: 'Indian Bread', name: 'Phulka', veg: 'Veg' },
  { id: 631, section: 'Indian Bread', name: 'Plain Naan', veg: 'Veg' },
  { id: 632, section: 'Indian Bread', name: 'Plain Paratha', veg: 'Veg' },
  { id: 633, section: 'Indian Bread', name: 'Poori', veg: 'Veg' },
  { id: 634, section: 'Indian Bread', name: 'Pudina Paratha', veg: 'Veg' },
  { id: 635, section: 'Indian Bread', name: 'Roti', veg: 'Veg' },
  { id: 636, section: 'Indian Bread', name: 'Rumali Roti', veg: 'Veg' },
  { id: 637, section: 'Indian Bread', name: 'Tandoori Roti', veg: 'Veg' },
  { id: 638, section: 'Raitha', name: 'Bhurani Raitha', veg: 'Veg' },
  { id: 639, section: 'Raitha', name: 'Boondi Raitha', veg: 'Veg' },
  { id: 640, section: 'Raitha', name: 'Cucumber Raitha', veg: 'Veg' },
  { id: 641, section: 'Raitha', name: 'Curd Raitha', veg: 'Veg' },
  { id: 642, section: 'Raitha', name: 'Mint Raitha', veg: 'Veg' },
  { id: 643, section: 'Raitha', name: 'Mixed Vegetable Raitha', veg: 'Veg' },
  { id: 644, section: 'Raitha', name: 'Onion Raitha', veg: 'Veg' },
  { id: 645, section: 'Raitha', name: 'Plain Raitha', veg: 'Veg' },
  { id: 646, section: 'Chutney', name: 'Beerakaya Tomato', veg: 'Veg' },
  { id: 647, section: 'Chutney', name: 'Dosa Avakaya', veg: 'Veg' },
  { id: 648, section: 'Chutney', name: 'Dosakaya Mukkalu', veg: 'Veg' },
  { id: 649, section: 'Chutney', name: 'Gongura Chutney', veg: 'Veg' },
  { id: 650, section: 'Chutney', name: 'Mango Turumu', veg: 'Veg' },
  { id: 651, section: 'Chutney', name: 'Pudina Chutney', veg: 'Veg' },
  { id: 652, section: 'Chutney', name: 'Tomato Coriander Chutney', veg: 'Veg' },
  { id: 653, section: 'Rasam / Pulusu', name: 'Gummadikaya Pulusu', veg: 'Veg' },
  { id: 654, section: 'Rasam / Pulusu', name: 'Mukkala Pulusu', veg: 'Veg' },
  { id: 655, section: 'Rasam / Pulusu', name: 'Pachi Pulusu', veg: 'Veg' },
  { id: 656, section: 'Rasam / Pulusu', name: 'Pappu Charu', veg: 'Veg' },
  { id: 657, section: 'Rasam / Pulusu', name: 'Pepper Rasam', veg: 'Veg' },
  { id: 658, section: 'Rasam / Pulusu', name: 'Sambar', veg: 'Veg' },
  { id: 659, section: 'Sweet / Dessert', name: 'Angoori Rasmalai', veg: 'Veg' },
  { id: 660, section: 'Sweet / Dessert', name: 'Apple And Cinnamon Cake', veg: 'Veg' },
  { id: 661, section: 'Sweet / Dessert', name: 'Assorted French Pastries', veg: 'Veg' },
  { id: 662, section: 'Sweet / Dessert', name: 'Assorted Pastries', veg: 'Veg' },
  { id: 663, section: 'Sweet / Dessert', name: 'Baked Gulab Jamun', veg: 'Veg' },
  { id: 664, section: 'Sweet / Dessert', name: 'Baked Rasgulla', veg: 'Veg' },
  { id: 665, section: 'Sweet / Dessert', name: 'Baked Yogurt With Seasonal Fruit', veg: 'Veg' },
  { id: 666, section: 'Sweet / Dessert', name: 'Black Forest Pastry', veg: 'Veg' },
  { id: 667, section: 'Sweet / Dessert', name: 'Bobbatlu', veg: 'Veg' },
  { id: 668, section: 'Sweet / Dessert', name: 'Bread And Butter Pudding', veg: 'Veg' },
  { id: 669, section: 'Sweet / Dessert', name: 'Butterscotch Gateaux', veg: 'Veg' },
  { id: 670, section: 'Sweet / Dessert', name: 'Carrot Halwa', veg: 'Veg' },
  { id: 671, section: 'Sweet / Dessert', name: 'Chakkera Pongali', veg: 'Veg' },
  { id: 672, section: 'Sweet / Dessert', name: 'Chocolate Caramel Mousse', veg: 'Veg' },
  { id: 673, section: 'Sweet / Dessert', name: 'Chocolate Marble Mud Cake', veg: 'Veg' },
  { id: 674, section: 'Sweet / Dessert', name: 'Chocolate Mud Brownie', veg: 'Veg' },
  { id: 675, section: 'Sweet / Dessert', name: 'Chocolate Mud Cake', veg: 'Veg' },
  { id: 676, section: 'Sweet / Dessert', name: 'Chocolate Steam Pudding', veg: 'Veg' },
  { id: 677, section: 'Sweet / Dessert', name: 'Chocolate Truffle Cake', veg: 'Veg' },
  { id: 678, section: 'Sweet / Dessert', name: 'Chocolate Walnut Brownie', veg: 'Veg' },
  { id: 679, section: 'Sweet / Dessert', name: 'Creme Brulee', veg: 'Veg' },
  { id: 680, section: 'Sweet / Dessert', name: 'Creme Caramel', veg: 'Veg' },
  { id: 681, section: 'Sweet / Dessert', name: 'Custard Fruit Salad', veg: 'Veg' },
  { id: 682, section: 'Sweet / Dessert', name: 'Doodhi Ka Halwa', veg: 'Veg' },
  { id: 683, section: 'Sweet / Dessert', name: 'Double Ka Meetha', veg: 'Veg' },
  { id: 684, section: 'Sweet / Dessert', name: 'Fresh Fruit Gateaux', veg: 'Veg' },
  { id: 685, section: 'Sweet / Dessert', name: 'Fruit Rabdi', veg: 'Veg' },
  { id: 686, section: 'Sweet / Dessert', name: 'Fruit Trifle', veg: 'Veg' },
  { id: 687, section: 'Sweet / Dessert', name: 'Gajar Ka Halwa', veg: 'Veg' },
  { id: 688, section: 'Sweet / Dessert', name: 'Gulab Jamun', veg: 'Veg' },
  { id: 689, section: 'Sweet / Dessert', name: 'Honey Nougat Parfait', veg: 'Veg' },
  { id: 690, section: 'Sweet / Dessert', name: 'Jalebi', veg: 'Veg' },
  { id: 691, section: 'Sweet / Dessert', name: 'Jalebi With Rabdi', veg: 'Veg' },
  { id: 692, section: 'Sweet / Dessert', name: 'Kaddu Ka Kheer', veg: 'Veg' },
  { id: 693, section: 'Sweet / Dessert', name: 'Kaddu Ki Kheer', veg: 'Veg' },
  { id: 694, section: 'Sweet / Dessert', name: 'Kala Jamun', veg: 'Veg' },
  { id: 695, section: 'Sweet / Dessert', name: 'Kesari Phirni', veg: 'Veg' },
  { id: 696, section: 'Sweet / Dessert', name: 'Khubani Ka Meetha', veg: 'Veg' },
  { id: 697, section: 'Sweet / Dessert', name: 'Malai Cham Cham', veg: 'Veg' },
  { id: 698, section: 'Sweet / Dessert', name: 'Malpua', veg: 'Veg' },
  { id: 699, section: 'Sweet / Dessert', name: 'Malpua With Rabdi', veg: 'Veg' },
  { id: 700, section: 'Sweet / Dessert', name: 'Mango Mousse', veg: 'Veg' },
  { id: 701, section: 'Sweet / Dessert', name: 'Mango Mousse Cake (Seasonal)', veg: 'Veg' },
  { id: 702, section: 'Sweet / Dessert', name: 'Moong Dal Halwa', veg: 'Veg' },
  { id: 703, section: 'Sweet / Dessert', name: 'Moong Dal Payasam', veg: 'Veg' },
  { id: 704, section: 'Sweet / Dessert', name: 'Palak Halwa', veg: 'Veg' },
  { id: 705, section: 'Sweet / Dessert', name: 'Payasam', veg: 'Veg' },
  { id: 706, section: 'Sweet / Dessert', name: 'Pineapple And Carrot Cake', veg: 'Veg' },
  { id: 707, section: 'Sweet / Dessert', name: 'Pineapple Pastry', veg: 'Veg' },
  { id: 708, section: 'Sweet / Dessert', name: 'Pineapple Upside Down Cake', veg: 'Veg' },
  { id: 709, section: 'Sweet / Dessert', name: 'Poornam Boorelu', veg: 'Veg' },
  { id: 710, section: 'Sweet / Dessert', name: 'Profiteroles With Chocolate Fudge', veg: 'Veg' },
  { id: 711, section: 'Sweet / Dessert', name: 'Rasgulla', veg: 'Veg' },
  { id: 712, section: 'Sweet / Dessert', name: 'Rasmalai', veg: 'Veg' },
  { id: 713, section: 'Sweet / Dessert', name: 'Semiya Payasam', veg: 'Veg' },
  { id: 714, section: 'Sweet / Dessert', name: 'Seviyan Payasam', veg: 'Veg' },
  { id: 715, section: 'Sweet / Dessert', name: 'Shahi Tukda', veg: 'Veg' },
  { id: 716, section: 'Sweet / Dessert', name: 'Sliced Fresh Fruit', veg: 'Veg' },
  { id: 717, section: 'Sweet / Dessert', name: 'Sticky Date Pudding', veg: 'Veg' },
  { id: 718, section: 'Sweet / Dessert', name: 'Tiramisu', veg: 'Veg' },
  { id: 719, section: 'Sweet / Dessert', name: 'Zauq-E-Shahi', veg: 'Veg' },
  { id: 720, section: 'Ice Cream', name: 'Butterscotch Ice Cream', veg: 'Veg' },
  { id: 721, section: 'Ice Cream', name: 'Chocolate Ice Cream', veg: 'Veg' },
  { id: 722, section: 'Ice Cream', name: 'Coffee Ice Cream', veg: 'Veg' },
  { id: 723, section: 'Ice Cream', name: 'Mango Ice Cream', veg: 'Veg' },
  { id: 724, section: 'Ice Cream', name: 'Strawberry Ice Cream', veg: 'Veg' },
  { id: 725, section: 'Ice Cream', name: 'Vanilla Ice Cream', veg: 'Veg' },
  { id: 726, section: 'Fresh Fruit', name: 'Grapes', veg: 'Veg' },
  { id: 727, section: 'Fresh Fruit', name: 'Karbuja', veg: 'Veg' },
  { id: 728, section: 'Fresh Fruit', name: 'Mango', veg: 'Veg' },
  { id: 729, section: 'Fresh Fruit', name: 'Papaya', veg: 'Veg' },
  { id: 730, section: 'Fresh Fruit', name: 'Pineapple', veg: 'Veg' },
  { id: 731, section: 'Fresh Fruit', name: 'Watermelon', veg: 'Veg' },
  { id: 732, section: 'Common Items / Accompaniments', name: 'Chutney', veg: 'Veg' },
  { id: 733, section: 'Common Items / Accompaniments', name: 'Cool Water & Bottles', veg: 'Veg' },
  { id: 734, section: 'Common Items / Accompaniments', name: 'Curd', veg: 'Veg' },
  { id: 735, section: 'Common Items / Accompaniments', name: 'Ghee', veg: 'Veg' },
  { id: 736, section: 'Common Items / Accompaniments', name: 'Mirchi Ka Salan', veg: 'Veg' },
  { id: 737, section: 'Common Items / Accompaniments', name: 'Mouth Freshener', veg: 'Veg' },
  { id: 738, section: 'Common Items / Accompaniments', name: 'Pan', veg: 'Veg' },
  { id: 739, section: 'Common Items / Accompaniments', name: 'Papad', veg: 'Veg' },
  { id: 740, section: 'Common Items / Accompaniments', name: 'Papad/Fryums', veg: 'Veg' },
  { id: 741, section: 'Common Items / Accompaniments', name: 'Pickle', veg: 'Veg' },
  { id: 742, section: 'Common Items / Accompaniments', name: 'Plain Curd', veg: 'Veg' },
  { id: 743, section: 'Common Items / Accompaniments', name: 'Plain Rice', veg: 'Veg' },
  { id: 744, section: 'Common Items / Accompaniments', name: 'Sweet Pan', veg: 'Veg' },
  { id: 745, section: 'Common Items / Accompaniments', name: 'Water Bottles', veg: 'Veg' },
  { id: 746, section: 'Common Items / Accompaniments', name: 'White Rice', veg: 'Veg' },
  { id: 747, section: 'Live Counter / Station', name: 'Appam Station', veg: 'Veg' },
  { id: 748, section: 'Live Counter / Station', name: 'Burmese Khao Suey Station', veg: 'Veg' },
  { id: 749, section: 'Live Counter / Station', name: 'Chat Station', veg: 'Veg' },
  { id: 750, section: 'Live Counter / Station', name: 'Dosa Trolley', veg: 'Veg' },
  { id: 751, section: 'Live Counter / Station', name: 'Hot Tawa Sweets Counter', veg: 'Veg' },
  { id: 752, section: 'Live Counter / Station', name: 'Kathi Roll Station', veg: 'Veg' },
  { id: 753, section: 'Live Counter / Station', name: 'Kothu Paratha Station', veg: 'Veg' },
  { id: 754, section: 'Live Counter / Station', name: 'Laksa Soup Station', veg: 'Veg' },
  { id: 755, section: 'Live Counter / Station', name: 'Mexican Station', veg: 'Veg' },
  { id: 756, section: 'Live Counter / Station', name: 'Mongolian Station', veg: 'Veg' },
  { id: 757, section: 'Live Counter / Station', name: 'Pancake Station', veg: 'Veg' },
  { id: 758, section: 'Live Counter / Station', name: 'Pav Bhaji Counter', veg: 'Veg' },
  { id: 759, section: 'Live Counter / Station', name: 'Pesarattu Station', veg: 'Veg' },
  { id: 760, section: 'Live Counter / Station', name: 'Tawa Subzi Counter', veg: 'Veg' },
  { id: 761, section: 'Live Counter / Station', name: 'Waffle Station', veg: 'Veg' },
  { id: 762, section: 'Add-On (Extra Charge)', name: 'Baby Corn Curry', veg: 'Veg' },
  { id: 763, section: 'Add-On (Extra Charge)', name: 'Extra Non-Veg Curry', veg: 'Veg' },
  { id: 764, section: 'Add-On (Extra Charge)', name: 'Extra Sweet', veg: 'Veg' },
  { id: 765, section: 'Add-On (Extra Charge)', name: 'Extra Veg Curry', veg: 'Veg' },
  { id: 766, section: 'Add-On (Extra Charge)', name: 'Fresh Fruit Counter', veg: 'Veg' },
  { id: 767, section: 'Add-On (Extra Charge)', name: 'Mushroom Curry', veg: 'Veg' },
]
