// AUTO-GENERATED from Pellikart_Dish_Bank.xlsx — do not edit by hand.
// 298 dishes across 15 sections, 7 cuisine styles, Veg/Non-Veg flag.

export interface Dish { id: number; section: string; name: string; style: string; veg: 'Veg' | 'Non-Veg'; description: string }

export const MENU_SECTIONS = ['Welcome Drinks', 'Soups & Salads', 'Starters / Appetizers', 'Chaat & Live Counters', 'Tiffins / Breakfast Items', 'Rice, Pulao & Biryani', 'Rotis & Indian Breads', 'Pappu, Dal & Lentils', 'Pulusu, Charu & Rasam', 'Curries (Gravy)', 'Fry / Vepudu (Dry)', 'Podi, Pachadi & Pickles', 'Accompaniments', 'Desserts & Sweets', 'Post-Meal'] as const

export const CUISINE_STYLES = ['Andhra Style', 'Godavari Style', 'Rayalaseema Style', 'Telangana Style', 'Hyderabadi', 'Pure-Veg Traditional', 'Others'] as const

export const DISH_BANK: Dish[] = [
  { id: 1, section: 'Welcome Drinks', name: 'Paanakam', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Jaggery, ginger & cardamom ritual cooler' },
  { id: 2, section: 'Welcome Drinks', name: 'Spiced Buttermilk (Majjiga)', style: 'Telangana Style', veg: 'Veg', description: 'Cumin & curry-leaf tempered buttermilk' },
  { id: 3, section: 'Welcome Drinks', name: 'Badam Milk', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Saffron almond milk' },
  { id: 4, section: 'Welcome Drinks', name: 'Rose Milk', style: 'Others', veg: 'Veg', description: 'Chilled milk with rose syrup' },
  { id: 5, section: 'Welcome Drinks', name: 'Nimmakaya Soda', style: 'Andhra Style', veg: 'Veg', description: 'Tangy lime soda with salt & masala' },
  { id: 6, section: 'Welcome Drinks', name: 'Watermelon Juice', style: 'Others', veg: 'Veg', description: 'Fresh watermelon juice' },
  { id: 7, section: 'Welcome Drinks', name: 'Tender Coconut Water', style: 'Others', veg: 'Veg', description: 'Served in shell or glass' },
  { id: 8, section: 'Welcome Drinks', name: 'Mango Lassi', style: 'Others', veg: 'Veg', description: 'Yogurt & mango blend' },
  { id: 9, section: 'Welcome Drinks', name: 'Sweet Lassi', style: 'Others', veg: 'Veg', description: 'Sweetened yogurt drink' },
  { id: 10, section: 'Welcome Drinks', name: 'Jaljeera', style: 'Others', veg: 'Veg', description: 'Spiced cumin-mint cooler' },
  { id: 11, section: 'Welcome Drinks', name: 'Aam Panna', style: 'Others', veg: 'Veg', description: 'Raw mango summer cooler' },
  { id: 12, section: 'Welcome Drinks', name: 'Sapota Milkshake', style: 'Others', veg: 'Veg', description: 'Chikoo blended shake' },
  { id: 13, section: 'Welcome Drinks', name: 'Filter Coffee', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'South Indian decoction coffee' },
  { id: 14, section: 'Welcome Drinks', name: 'Masala Chai', style: 'Others', veg: 'Veg', description: 'Spiced milk tea' },
  { id: 15, section: 'Welcome Drinks', name: 'Mosambi Juice', style: 'Others', veg: 'Veg', description: 'Sweet lime juice' },
  { id: 16, section: 'Welcome Drinks', name: 'Pineapple Juice', style: 'Others', veg: 'Veg', description: 'Fresh pineapple juice' },
  { id: 17, section: 'Welcome Drinks', name: 'Virgin Mojito', style: 'Others', veg: 'Veg', description: 'Mint & lime mocktail' },
  { id: 18, section: 'Welcome Drinks', name: 'Blue Lagoon Mocktail', style: 'Others', veg: 'Veg', description: 'Citrus blue-curacao mocktail' },
  { id: 19, section: 'Welcome Drinks', name: 'Fruit Punch', style: 'Others', veg: 'Veg', description: 'Mixed fruit cooler' },
  { id: 20, section: 'Welcome Drinks', name: 'Thandai', style: 'Others', veg: 'Veg', description: 'Spiced nut-milk drink' },
  { id: 21, section: 'Soups & Salads', name: 'Sweet Corn Soup', style: 'Others', veg: 'Veg', description: 'Creamy corn soup' },
  { id: 22, section: 'Soups & Salads', name: 'Hot & Sour Soup', style: 'Others', veg: 'Veg', description: 'Tangy-spicy Indo-Chinese soup' },
  { id: 23, section: 'Soups & Salads', name: 'Manchow Soup', style: 'Others', veg: 'Veg', description: 'Soup topped with fried noodles' },
  { id: 24, section: 'Soups & Salads', name: 'Veg Clear Soup', style: 'Others', veg: 'Veg', description: 'Light vegetable broth' },
  { id: 25, section: 'Soups & Salads', name: 'Cream of Mushroom Soup', style: 'Others', veg: 'Veg', description: 'Creamy mushroom soup' },
  { id: 26, section: 'Soups & Salads', name: 'Lemon Coriander Soup', style: 'Others', veg: 'Veg', description: 'Tangy herb soup' },
  { id: 27, section: 'Soups & Salads', name: 'Tomato Shorba', style: 'Others', veg: 'Veg', description: 'Spiced tomato broth' },
  { id: 28, section: 'Soups & Salads', name: 'Murgh Shorba', style: 'Hyderabadi', veg: 'Non-Veg', description: 'Spiced chicken broth' },
  { id: 29, section: 'Soups & Salads', name: 'Mutton Paya Shorba', style: 'Hyderabadi', veg: 'Non-Veg', description: 'Slow-cooked trotter soup' },
  { id: 30, section: 'Soups & Salads', name: 'Talumein Soup', style: 'Others', veg: 'Veg', description: 'Noodle-based clear soup' },
  { id: 31, section: 'Soups & Salads', name: 'Green Garden Salad', style: 'Others', veg: 'Veg', description: 'Fresh cut vegetables' },
  { id: 32, section: 'Soups & Salads', name: 'Russian Salad', style: 'Others', veg: 'Veg', description: 'Veg & mayonnaise salad' },
  { id: 33, section: 'Soups & Salads', name: 'Kosambari', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Soaked moong dal & cucumber salad' },
  { id: 34, section: 'Soups & Salads', name: 'Sprouts Salad', style: 'Others', veg: 'Veg', description: 'Mixed sprouts salad' },
  { id: 35, section: 'Soups & Salads', name: 'Corn & Capsicum Salad', style: 'Others', veg: 'Veg', description: 'Sweet corn & capsicum mix' },
  { id: 36, section: 'Soups & Salads', name: 'Greek Salad', style: 'Others', veg: 'Veg', description: 'Cucumber, olives & feta' },
  { id: 37, section: 'Soups & Salads', name: 'Caesar Salad', style: 'Others', veg: 'Veg', description: 'Lettuce with creamy dressing' },
  { id: 38, section: 'Soups & Salads', name: 'Beetroot Carrot Salad', style: 'Others', veg: 'Veg', description: 'Grated beet & carrot salad' },
  { id: 39, section: 'Soups & Salads', name: 'Pasta Salad', style: 'Others', veg: 'Veg', description: 'Cold pasta salad' },
  { id: 40, section: 'Soups & Salads', name: 'Fruit Salad', style: 'Others', veg: 'Veg', description: 'Mixed seasonal fruit salad' },
  { id: 41, section: 'Starters / Appetizers', name: 'Paneer Tikka', style: 'Others', veg: 'Veg', description: 'Grilled marinated cottage cheese' },
  { id: 42, section: 'Starters / Appetizers', name: 'Veg Manchurian', style: 'Others', veg: 'Veg', description: 'Fried veg balls in soy sauce' },
  { id: 43, section: 'Starters / Appetizers', name: 'Gobi 65', style: 'Others', veg: 'Veg', description: 'Spicy fried cauliflower' },
  { id: 44, section: 'Starters / Appetizers', name: 'Hara Bhara Kebab', style: 'Others', veg: 'Veg', description: 'Spinach & green-pea patties' },
  { id: 45, section: 'Starters / Appetizers', name: 'Mirchi Bajji', style: 'Telangana Style', veg: 'Veg', description: 'Stuffed chilli fritters' },
  { id: 46, section: 'Starters / Appetizers', name: 'Punugulu', style: 'Godavari Style', veg: 'Veg', description: 'Crispy fried lentil-batter balls' },
  { id: 47, section: 'Starters / Appetizers', name: 'Crispy Corn', style: 'Others', veg: 'Veg', description: 'Deep-fried seasoned corn' },
  { id: 48, section: 'Starters / Appetizers', name: 'Mushroom 65', style: 'Andhra Style', veg: 'Veg', description: 'Spicy fried mushroom' },
  { id: 49, section: 'Starters / Appetizers', name: 'Chilli Paneer', style: 'Others', veg: 'Veg', description: 'Indo-Chinese paneer starter' },
  { id: 50, section: 'Starters / Appetizers', name: 'Aloo 65', style: 'Others', veg: 'Veg', description: 'Spicy fried potato' },
  { id: 51, section: 'Starters / Appetizers', name: 'Chicken 65', style: 'Andhra Style', veg: 'Non-Veg', description: 'Spicy deep-fried chicken, curry-leaf tempered' },
  { id: 52, section: 'Starters / Appetizers', name: 'Chicken Majestic', style: 'Hyderabadi', veg: 'Non-Veg', description: 'Crispy chicken in yogurt-chilli toss' },
  { id: 53, section: 'Starters / Appetizers', name: 'Apollo Fish', style: 'Andhra Style', veg: 'Non-Veg', description: 'Crispy batter-fried fish' },
  { id: 54, section: 'Starters / Appetizers', name: 'Country Chicken Fry', style: 'Rayalaseema Style', veg: 'Non-Veg', description: 'Spicy natu kodi dry fry' },
  { id: 55, section: 'Starters / Appetizers', name: 'Murgh Malai Kebab', style: 'Hyderabadi', veg: 'Non-Veg', description: 'Creamy grilled chicken kebab' },
  { id: 56, section: 'Starters / Appetizers', name: 'Mutton Shikampuri Kebab', style: 'Hyderabadi', veg: 'Non-Veg', description: 'Soft minced-mutton kebab' },
  { id: 57, section: 'Starters / Appetizers', name: 'Prawn Fry (Royyala Vepudu)', style: 'Godavari Style', veg: 'Non-Veg', description: 'Crisp masala prawn fry' },
  { id: 58, section: 'Starters / Appetizers', name: 'Fish Tikka', style: 'Others', veg: 'Non-Veg', description: 'Grilled marinated fish' },
  { id: 59, section: 'Starters / Appetizers', name: 'Tangdi Kebab', style: 'Hyderabadi', veg: 'Non-Veg', description: 'Grilled chicken drumstick' },
  { id: 60, section: 'Starters / Appetizers', name: 'Chicken Lollipop', style: 'Others', veg: 'Non-Veg', description: 'Frenched chicken wings, fried' },
  { id: 61, section: 'Chaat & Live Counters', name: 'Pani Puri / Golgappa', style: 'Others', veg: 'Veg', description: 'Crisp puris with spiced water' },
  { id: 62, section: 'Chaat & Live Counters', name: 'Bhel Puri', style: 'Others', veg: 'Veg', description: 'Puffed rice chaat' },
  { id: 63, section: 'Chaat & Live Counters', name: 'Sev Puri', style: 'Others', veg: 'Veg', description: 'Puri topped with sev & chutneys' },
  { id: 64, section: 'Chaat & Live Counters', name: 'Dahi Puri', style: 'Others', veg: 'Veg', description: 'Puri with yogurt & chutneys' },
  { id: 65, section: 'Chaat & Live Counters', name: 'Samosa Chaat', style: 'Others', veg: 'Veg', description: 'Crushed samosa with toppings' },
  { id: 66, section: 'Chaat & Live Counters', name: 'Aloo Tikki Chaat', style: 'Others', veg: 'Veg', description: 'Potato patty chaat' },
  { id: 67, section: 'Chaat & Live Counters', name: 'Pav Bhaji', style: 'Others', veg: 'Veg', description: 'Spiced veg mash with buttered buns' },
  { id: 68, section: 'Chaat & Live Counters', name: 'Ragda Pattice', style: 'Others', veg: 'Veg', description: 'Potato patty in white-pea curry' },
  { id: 69, section: 'Chaat & Live Counters', name: 'Dahi Vada', style: 'Others', veg: 'Veg', description: 'Lentil dumplings in yogurt' },
  { id: 70, section: 'Chaat & Live Counters', name: 'Chaat Papdi', style: 'Others', veg: 'Veg', description: 'Crisp wafers with chutney & yogurt' },
  { id: 71, section: 'Chaat & Live Counters', name: 'Punugulu Counter', style: 'Godavari Style', veg: 'Veg', description: 'Live-fried lentil-batter balls' },
  { id: 72, section: 'Chaat & Live Counters', name: 'Mirchi Bajji Counter', style: 'Telangana Style', veg: 'Veg', description: 'Live-fried stuffed chilli fritters' },
  { id: 73, section: 'Chaat & Live Counters', name: 'Mysore Bonda', style: 'Others', veg: 'Veg', description: 'Fried fluffy batter dumplings' },
  { id: 74, section: 'Chaat & Live Counters', name: 'Cut Mirchi', style: 'Hyderabadi', veg: 'Veg', description: 'Sliced green chilli fritters' },
  { id: 75, section: 'Chaat & Live Counters', name: 'Live Dosa Counter', style: 'Others', veg: 'Veg', description: 'Made-to-order dosa station' },
  { id: 76, section: 'Chaat & Live Counters', name: 'Live Pasta Counter', style: 'Others', veg: 'Veg', description: 'Made-to-order pasta station' },
  { id: 77, section: 'Chaat & Live Counters', name: 'Tandoori Counter', style: 'Others', veg: 'Veg', description: 'Live tandoor grilling station' },
  { id: 78, section: 'Chaat & Live Counters', name: 'Pizza Counter', style: 'Others', veg: 'Veg', description: 'Live wood-fired pizza station' },
  { id: 79, section: 'Chaat & Live Counters', name: 'Tawa Pulao Counter', style: 'Others', veg: 'Veg', description: 'Live griddle pulao station' },
  { id: 80, section: 'Chaat & Live Counters', name: 'Live Jalebi Counter', style: 'Others', veg: 'Veg', description: 'Fresh hot jalebi station' },
  { id: 81, section: 'Tiffins / Breakfast Items', name: 'Idli', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Steamed rice-lentil cakes' },
  { id: 82, section: 'Tiffins / Breakfast Items', name: 'Plain Dosa', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Crisp rice-lentil crepe' },
  { id: 83, section: 'Tiffins / Breakfast Items', name: 'Masala Dosa', style: 'Others', veg: 'Veg', description: 'Dosa with spiced potato filling' },
  { id: 84, section: 'Tiffins / Breakfast Items', name: 'Onion Dosa', style: 'Others', veg: 'Veg', description: 'Dosa topped with onion' },
  { id: 85, section: 'Tiffins / Breakfast Items', name: 'Pesarattu', style: 'Andhra Style', veg: 'Veg', description: 'Green-gram dosa' },
  { id: 86, section: 'Tiffins / Breakfast Items', name: 'MLA Pesarattu', style: 'Andhra Style', veg: 'Veg', description: 'Pesarattu with upma stuffing' },
  { id: 87, section: 'Tiffins / Breakfast Items', name: 'Upma', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Semolina savory porridge' },
  { id: 88, section: 'Tiffins / Breakfast Items', name: 'Medu Vada (Garelu)', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Fried urad-dal doughnuts' },
  { id: 89, section: 'Tiffins / Breakfast Items', name: 'Uttapam', style: 'Others', veg: 'Veg', description: 'Thick dosa with toppings' },
  { id: 90, section: 'Tiffins / Breakfast Items', name: 'Rava Dosa', style: 'Others', veg: 'Veg', description: 'Crisp semolina crepe' },
  { id: 91, section: 'Tiffins / Breakfast Items', name: 'Set Dosa', style: 'Others', veg: 'Veg', description: 'Soft spongy mini dosas' },
  { id: 92, section: 'Tiffins / Breakfast Items', name: 'Ven Pongal', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Rice-lentil savory pongal' },
  { id: 93, section: 'Tiffins / Breakfast Items', name: 'Poha', style: 'Others', veg: 'Veg', description: 'Flattened rice tempered dish' },
  { id: 94, section: 'Tiffins / Breakfast Items', name: 'Sarva Pindi', style: 'Telangana Style', veg: 'Veg', description: 'Spiced rice-flour griddle pancake' },
  { id: 95, section: 'Tiffins / Breakfast Items', name: 'Idiyappam', style: 'Others', veg: 'Veg', description: 'Steamed rice string hoppers' },
  { id: 96, section: 'Tiffins / Breakfast Items', name: 'Appam', style: 'Others', veg: 'Veg', description: 'Fermented rice pancake' },
  { id: 97, section: 'Tiffins / Breakfast Items', name: 'Puri with Aloo Kurma', style: 'Others', veg: 'Veg', description: 'Fried bread with potato curry' },
  { id: 98, section: 'Tiffins / Breakfast Items', name: 'Aloo Bonda', style: 'Others', veg: 'Veg', description: 'Battered fried potato dumpling' },
  { id: 99, section: 'Tiffins / Breakfast Items', name: 'Semiya Upma', style: 'Others', veg: 'Veg', description: 'Vermicelli savory dish' },
  { id: 100, section: 'Tiffins / Breakfast Items', name: 'Sabudana Khichdi', style: 'Others', veg: 'Veg', description: 'Sago & peanut tempered dish' },
  { id: 101, section: 'Rice, Pulao & Biryani', name: 'Steamed Rice', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Plain boiled rice' },
  { id: 102, section: 'Rice, Pulao & Biryani', name: 'Jeera Rice', style: 'Others', veg: 'Veg', description: 'Cumin-tempered rice' },
  { id: 103, section: 'Rice, Pulao & Biryani', name: 'Ghee Rice', style: 'Others', veg: 'Veg', description: 'Mildly spiced ghee rice' },
  { id: 104, section: 'Rice, Pulao & Biryani', name: 'Pulihora (Tamarind Rice)', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Tangy tamarind rice' },
  { id: 105, section: 'Rice, Pulao & Biryani', name: 'Daddojanam (Curd Rice)', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Tempered yogurt rice' },
  { id: 106, section: 'Rice, Pulao & Biryani', name: 'Kobbari Annam (Coconut Rice)', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Coconut-flavored rice' },
  { id: 107, section: 'Rice, Pulao & Biryani', name: 'Nimmakaya Pulihora (Lemon Rice)', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Tangy lemon rice' },
  { id: 108, section: 'Rice, Pulao & Biryani', name: 'Pudina Rice', style: 'Others', veg: 'Veg', description: 'Mint-flavored rice' },
  { id: 109, section: 'Rice, Pulao & Biryani', name: 'Veg Pulao', style: 'Others', veg: 'Veg', description: 'Mixed-vegetable pilaf' },
  { id: 110, section: 'Rice, Pulao & Biryani', name: 'Bagara Annam', style: 'Hyderabadi', veg: 'Veg', description: 'Mildly spiced rice, served with salan' },
  { id: 111, section: 'Rice, Pulao & Biryani', name: 'Kaju Veg Dum Biryani', style: 'Others', veg: 'Veg', description: 'Cashew & vegetable dum biryani' },
  { id: 112, section: 'Rice, Pulao & Biryani', name: 'Hyderabadi Veg Dum Biryani', style: 'Hyderabadi', veg: 'Veg', description: 'Layered vegetable dum biryani' },
  { id: 113, section: 'Rice, Pulao & Biryani', name: 'Paneer Biryani', style: 'Others', veg: 'Veg', description: 'Cottage-cheese biryani' },
  { id: 114, section: 'Rice, Pulao & Biryani', name: 'Hyderabadi Chicken Dum Biryani', style: 'Hyderabadi', veg: 'Non-Veg', description: 'Classic layered chicken dum biryani' },
  { id: 115, section: 'Rice, Pulao & Biryani', name: 'Hyderabadi Mutton Dum Biryani', style: 'Hyderabadi', veg: 'Non-Veg', description: 'Classic layered mutton dum biryani' },
  { id: 116, section: 'Rice, Pulao & Biryani', name: 'Gongura Chicken Biryani', style: 'Andhra Style', veg: 'Non-Veg', description: 'Sorrel-leaf spiced chicken biryani' },
  { id: 117, section: 'Rice, Pulao & Biryani', name: 'Natu Kodi Biryani', style: 'Rayalaseema Style', veg: 'Non-Veg', description: 'Country chicken biryani' },
  { id: 118, section: 'Rice, Pulao & Biryani', name: 'Prawn Biryani', style: 'Godavari Style', veg: 'Non-Veg', description: 'Coastal-style prawn biryani' },
  { id: 119, section: 'Rice, Pulao & Biryani', name: 'Ulavacharu Biryani', style: 'Godavari Style', veg: 'Non-Veg', description: 'Biryani served with horse-gram broth' },
  { id: 120, section: 'Rice, Pulao & Biryani', name: 'Avakaya Biryani', style: 'Andhra Style', veg: 'Non-Veg', description: 'Mango-pickle spiced biryani' },
  { id: 121, section: 'Rotis & Indian Breads', name: 'Pulka (Phulka)', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Soft puffed wheat flatbread' },
  { id: 122, section: 'Rotis & Indian Breads', name: 'Chapati', style: 'Others', veg: 'Veg', description: 'Everyday wheat flatbread' },
  { id: 123, section: 'Rotis & Indian Breads', name: 'Tandoori Roti', style: 'Others', veg: 'Veg', description: 'Clay-oven baked roti' },
  { id: 124, section: 'Rotis & Indian Breads', name: 'Butter Naan', style: 'Others', veg: 'Veg', description: 'Soft leavened bread with butter' },
  { id: 125, section: 'Rotis & Indian Breads', name: 'Garlic Naan', style: 'Others', veg: 'Veg', description: 'Naan topped with garlic' },
  { id: 126, section: 'Rotis & Indian Breads', name: 'Rumali Roti', style: 'Hyderabadi', veg: 'Veg', description: 'Thin handkerchief-soft bread' },
  { id: 127, section: 'Rotis & Indian Breads', name: 'Sheermal', style: 'Hyderabadi', veg: 'Veg', description: 'Mildly sweet saffron flatbread' },
  { id: 128, section: 'Rotis & Indian Breads', name: 'Lachha Paratha', style: 'Others', veg: 'Veg', description: 'Flaky layered paratha' },
  { id: 129, section: 'Rotis & Indian Breads', name: 'Pudina Paratha', style: 'Others', veg: 'Veg', description: 'Mint-flavored paratha' },
  { id: 130, section: 'Rotis & Indian Breads', name: 'Aloo Paratha', style: 'Others', veg: 'Veg', description: 'Potato-stuffed paratha' },
  { id: 131, section: 'Rotis & Indian Breads', name: 'Methi Paratha', style: 'Others', veg: 'Veg', description: 'Fenugreek-flavored paratha' },
  { id: 132, section: 'Rotis & Indian Breads', name: 'Missi Roti', style: 'Others', veg: 'Veg', description: 'Gram-flour spiced roti' },
  { id: 133, section: 'Rotis & Indian Breads', name: 'Kulcha', style: 'Others', veg: 'Veg', description: 'Soft leavened white-flour bread' },
  { id: 134, section: 'Rotis & Indian Breads', name: 'Jonna Rotte', style: 'Telangana Style', veg: 'Veg', description: 'Sorghum/jowar flatbread' },
  { id: 135, section: 'Rotis & Indian Breads', name: 'Sajja Rotte', style: 'Telangana Style', veg: 'Veg', description: 'Pearl-millet/bajra flatbread' },
  { id: 136, section: 'Rotis & Indian Breads', name: 'Ragi Roti', style: 'Rayalaseema Style', veg: 'Veg', description: 'Finger-millet flatbread' },
  { id: 137, section: 'Rotis & Indian Breads', name: 'Tandoori Aloo Kulcha', style: 'Others', veg: 'Veg', description: 'Potato-stuffed baked kulcha' },
  { id: 138, section: 'Rotis & Indian Breads', name: 'Ajwain Paratha', style: 'Others', veg: 'Veg', description: 'Carom-seed flavored paratha' },
  { id: 139, section: 'Rotis & Indian Breads', name: 'Makki Roti', style: 'Others', veg: 'Veg', description: 'Cornmeal flatbread' },
  { id: 140, section: 'Rotis & Indian Breads', name: 'Plain Naan', style: 'Others', veg: 'Veg', description: 'Soft leavened flatbread' },
  { id: 141, section: 'Pappu, Dal & Lentils', name: 'Tomato Pappu', style: 'Andhra Style', veg: 'Veg', description: 'Toor dal cooked with tomato' },
  { id: 142, section: 'Pappu, Dal & Lentils', name: 'Mamidikaya Pappu', style: 'Andhra Style', veg: 'Veg', description: 'Raw mango dal' },
  { id: 143, section: 'Pappu, Dal & Lentils', name: 'Gongura Pappu', style: 'Andhra Style', veg: 'Veg', description: 'Sorrel-leaf dal' },
  { id: 144, section: 'Pappu, Dal & Lentils', name: 'Palakura Pappu', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Spinach dal' },
  { id: 145, section: 'Pappu, Dal & Lentils', name: 'Dosakaya Pappu', style: 'Andhra Style', veg: 'Veg', description: 'Yellow-cucumber dal' },
  { id: 146, section: 'Pappu, Dal & Lentils', name: 'Sorakaya Pappu', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Bottle-gourd dal' },
  { id: 147, section: 'Pappu, Dal & Lentils', name: 'Totakura Pappu', style: 'Andhra Style', veg: 'Veg', description: 'Amaranth-leaf dal' },
  { id: 148, section: 'Pappu, Dal & Lentils', name: 'Chukkakura Pappu', style: 'Telangana Style', veg: 'Veg', description: 'Green-sorrel dal' },
  { id: 149, section: 'Pappu, Dal & Lentils', name: 'Beerakaya Pappu', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Ridge-gourd dal' },
  { id: 150, section: 'Pappu, Dal & Lentils', name: 'Munakkaya Pappu', style: 'Andhra Style', veg: 'Veg', description: 'Drumstick dal' },
  { id: 151, section: 'Pappu, Dal & Lentils', name: 'Bachalikura Pappu', style: 'Telangana Style', veg: 'Veg', description: 'Malabar-spinach dal' },
  { id: 152, section: 'Pappu, Dal & Lentils', name: 'Menthikura Pappu', style: 'Telangana Style', veg: 'Veg', description: 'Fenugreek-leaf dal' },
  { id: 153, section: 'Pappu, Dal & Lentils', name: 'Mudda Pappu', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Plain mashed toor dal with ghee' },
  { id: 154, section: 'Pappu, Dal & Lentils', name: 'Pesara Pappu', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Yellow moong dal preparation' },
  { id: 155, section: 'Pappu, Dal & Lentils', name: 'Sambar', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Lentil & vegetable stew' },
  { id: 156, section: 'Pappu, Dal & Lentils', name: 'Dal Tadka', style: 'Others', veg: 'Veg', description: 'Tempered yellow dal' },
  { id: 157, section: 'Pappu, Dal & Lentils', name: 'Dal Fry', style: 'Others', veg: 'Veg', description: 'Sauteed spiced dal' },
  { id: 158, section: 'Pappu, Dal & Lentils', name: 'Dal Makhani', style: 'Others', veg: 'Veg', description: 'Creamy black-lentil dal' },
  { id: 159, section: 'Pappu, Dal & Lentils', name: 'Vankaya Pappu', style: 'Andhra Style', veg: 'Veg', description: 'Brinjal dal' },
  { id: 160, section: 'Pappu, Dal & Lentils', name: 'Cabbage Pappu', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Cabbage dal' },
  { id: 161, section: 'Pulusu, Charu & Rasam', name: 'Mamidikaya Pulusu', style: 'Andhra Style', veg: 'Veg', description: 'Raw mango tamarind stew' },
  { id: 162, section: 'Pulusu, Charu & Rasam', name: 'Gongura Pulusu', style: 'Andhra Style', veg: 'Veg', description: 'Sorrel-leaf tangy stew' },
  { id: 163, section: 'Pulusu, Charu & Rasam', name: 'Chintakaya Pulusu', style: 'Andhra Style', veg: 'Veg', description: 'Tamarind-based stew' },
  { id: 164, section: 'Pulusu, Charu & Rasam', name: 'Vankaya Pulusu', style: 'Godavari Style', veg: 'Veg', description: 'Brinjal tamarind stew' },
  { id: 165, section: 'Pulusu, Charu & Rasam', name: 'Tomato Pulusu', style: 'Andhra Style', veg: 'Veg', description: 'Tomato tangy stew' },
  { id: 166, section: 'Pulusu, Charu & Rasam', name: 'Sorakaya Pulusu', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Bottle-gourd stew' },
  { id: 167, section: 'Pulusu, Charu & Rasam', name: 'Majjiga Pulusu', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Yogurt & vegetable curry' },
  { id: 168, section: 'Pulusu, Charu & Rasam', name: 'Dappalam', style: 'Godavari Style', veg: 'Veg', description: 'Mixed-vegetable tangy-sweet pulusu' },
  { id: 169, section: 'Pulusu, Charu & Rasam', name: 'Pappu Charu', style: 'Andhra Style', veg: 'Veg', description: 'Thin spiced lentil broth' },
  { id: 170, section: 'Pulusu, Charu & Rasam', name: 'Tomato Rasam', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Tangy tomato rasam' },
  { id: 171, section: 'Pulusu, Charu & Rasam', name: 'Miriyala Rasam', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Black-pepper rasam' },
  { id: 172, section: 'Pulusu, Charu & Rasam', name: 'Lemon Rasam', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Lemon-flavored rasam' },
  { id: 173, section: 'Pulusu, Charu & Rasam', name: 'Charu (Plain)', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Classic tamarind rasam' },
  { id: 174, section: 'Pulusu, Charu & Rasam', name: 'Ulava Charu', style: 'Godavari Style', veg: 'Veg', description: 'Horse-gram broth, Godavari signature' },
  { id: 175, section: 'Pulusu, Charu & Rasam', name: 'Pachi Pulusu', style: 'Telangana Style', veg: 'Veg', description: 'Raw tamarind-onion rasam' },
  { id: 176, section: 'Pulusu, Charu & Rasam', name: 'Kobbari Pulusu', style: 'Godavari Style', veg: 'Veg', description: 'Coconut-based pulusu' },
  { id: 177, section: 'Pulusu, Charu & Rasam', name: 'Chepala Pulusu', style: 'Godavari Style', veg: 'Non-Veg', description: 'Tamarind fish curry' },
  { id: 178, section: 'Pulusu, Charu & Rasam', name: 'Natu Kodi Pulusu', style: 'Rayalaseema Style', veg: 'Non-Veg', description: 'Spicy country chicken stew' },
  { id: 179, section: 'Pulusu, Charu & Rasam', name: 'Mutton Pulusu', style: 'Telangana Style', veg: 'Non-Veg', description: 'Tangy mutton stew' },
  { id: 180, section: 'Pulusu, Charu & Rasam', name: 'Royyala Pulusu', style: 'Andhra Style', veg: 'Non-Veg', description: 'Prawn tamarind curry' },
  { id: 181, section: 'Curries (Gravy)', name: 'Gutti Vankaya Koora', style: 'Andhra Style', veg: 'Veg', description: 'Stuffed baby brinjal curry' },
  { id: 182, section: 'Curries (Gravy)', name: 'Bagara Baingan', style: 'Hyderabadi', veg: 'Veg', description: 'Brinjal in peanut-sesame gravy' },
  { id: 183, section: 'Curries (Gravy)', name: 'Mirchi ka Salan', style: 'Hyderabadi', veg: 'Veg', description: 'Chilli & peanut curry, biryani side' },
  { id: 184, section: 'Curries (Gravy)', name: 'Aloo Kurma', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Potato in mild coconut gravy' },
  { id: 185, section: 'Curries (Gravy)', name: 'Mixed Veg Kurma', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Vegetables in coconut gravy' },
  { id: 186, section: 'Curries (Gravy)', name: 'Paneer Butter Masala', style: 'Others', veg: 'Veg', description: 'Paneer in creamy tomato gravy' },
  { id: 187, section: 'Curries (Gravy)', name: 'Kadai Paneer', style: 'Others', veg: 'Veg', description: 'Paneer with capsicum & spices' },
  { id: 188, section: 'Curries (Gravy)', name: 'Palak Paneer', style: 'Others', veg: 'Veg', description: 'Paneer in spinach gravy' },
  { id: 189, section: 'Curries (Gravy)', name: 'Navratan Korma', style: 'Others', veg: 'Veg', description: 'Nine-vegetable creamy curry' },
  { id: 190, section: 'Curries (Gravy)', name: 'Chana Masala', style: 'Others', veg: 'Veg', description: 'Spiced chickpea curry' },
  { id: 191, section: 'Curries (Gravy)', name: 'Dum Aloo', style: 'Others', veg: 'Veg', description: 'Baby potatoes in rich gravy' },
  { id: 192, section: 'Curries (Gravy)', name: 'Bendakaya Masala', style: 'Andhra Style', veg: 'Veg', description: 'Okra masala curry' },
  { id: 193, section: 'Curries (Gravy)', name: 'Sorakaya Kurma', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Bottle-gourd in mild gravy' },
  { id: 194, section: 'Curries (Gravy)', name: 'Dondakaya Koora', style: 'Andhra Style', veg: 'Veg', description: 'Ivy-gourd curry' },
  { id: 195, section: 'Curries (Gravy)', name: 'Kodi Kura (Andhra Chicken Curry)', style: 'Andhra Style', veg: 'Non-Veg', description: 'Fiery red Andhra chicken curry' },
  { id: 196, section: 'Curries (Gravy)', name: 'Natu Kodi Kura', style: 'Rayalaseema Style', veg: 'Non-Veg', description: 'Country chicken curry' },
  { id: 197, section: 'Curries (Gravy)', name: 'Gongura Mamsam', style: 'Andhra Style', veg: 'Non-Veg', description: 'Mutton cooked with sorrel leaves' },
  { id: 198, section: 'Curries (Gravy)', name: 'Mutton Curry', style: 'Telangana Style', veg: 'Non-Veg', description: 'Slow-cooked spiced mutton' },
  { id: 199, section: 'Curries (Gravy)', name: 'Dum ka Murgh', style: 'Hyderabadi', veg: 'Non-Veg', description: 'Slow-cooked chicken in rich gravy' },
  { id: 200, section: 'Curries (Gravy)', name: 'Royyala Iguru', style: 'Godavari Style', veg: 'Non-Veg', description: 'Semi-dry prawn curry' },
  { id: 201, section: 'Fry / Vepudu (Dry)', name: 'Aloo Vepudu', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Crisp potato fry' },
  { id: 202, section: 'Fry / Vepudu (Dry)', name: 'Bendakaya Vepudu', style: 'Andhra Style', veg: 'Veg', description: 'Okra dry fry' },
  { id: 203, section: 'Fry / Vepudu (Dry)', name: 'Dondakaya Vepudu', style: 'Andhra Style', veg: 'Veg', description: 'Ivy-gourd dry fry' },
  { id: 204, section: 'Fry / Vepudu (Dry)', name: 'Vankaya Vepudu', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Brinjal dry fry' },
  { id: 205, section: 'Fry / Vepudu (Dry)', name: 'Cabbage Vepudu', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Tempered cabbage fry' },
  { id: 206, section: 'Fry / Vepudu (Dry)', name: 'Beans Carrot Vepudu', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Beans & carrot poriyal-style fry' },
  { id: 207, section: 'Fry / Vepudu (Dry)', name: 'Kakarakaya Vepudu', style: 'Telangana Style', veg: 'Veg', description: 'Bitter-gourd fry' },
  { id: 208, section: 'Fry / Vepudu (Dry)', name: 'Aratikaya Vepudu', style: 'Andhra Style', veg: 'Veg', description: 'Raw banana fry' },
  { id: 209, section: 'Fry / Vepudu (Dry)', name: 'Chama Dumpa Vepudu', style: 'Andhra Style', veg: 'Veg', description: 'Colocasia/arbi crisp fry' },
  { id: 210, section: 'Fry / Vepudu (Dry)', name: 'Goruchikkudu Vepudu', style: 'Telangana Style', veg: 'Veg', description: 'Cluster-beans fry' },
  { id: 211, section: 'Fry / Vepudu (Dry)', name: 'Capsicum Vepudu', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Spiced capsicum fry' },
  { id: 212, section: 'Fry / Vepudu (Dry)', name: 'Dosakaya Vepudu', style: 'Andhra Style', veg: 'Veg', description: 'Yellow-cucumber fry' },
  { id: 213, section: 'Fry / Vepudu (Dry)', name: 'Kodi Vepudu (Chicken Fry)', style: 'Andhra Style', veg: 'Non-Veg', description: 'Spicy dry chicken fry' },
  { id: 214, section: 'Fry / Vepudu (Dry)', name: 'Natu Kodi Vepudu', style: 'Rayalaseema Style', veg: 'Non-Veg', description: 'Country chicken dry fry' },
  { id: 215, section: 'Fry / Vepudu (Dry)', name: 'Mutton Fry (Mamsam Vepudu)', style: 'Rayalaseema Style', veg: 'Non-Veg', description: 'Spicy dry mutton fry' },
  { id: 216, section: 'Fry / Vepudu (Dry)', name: 'Royyala Vepudu (Prawn Fry)', style: 'Godavari Style', veg: 'Non-Veg', description: 'Masala prawn fry' },
  { id: 217, section: 'Fry / Vepudu (Dry)', name: 'Chepala Vepudu (Fish Fry)', style: 'Godavari Style', veg: 'Non-Veg', description: 'Crisp shallow-fried fish' },
  { id: 218, section: 'Fry / Vepudu (Dry)', name: 'Boti Fry', style: 'Telangana Style', veg: 'Non-Veg', description: 'Spiced mutton-tripe fry' },
  { id: 219, section: 'Fry / Vepudu (Dry)', name: 'Kodi Guddu Vepudu (Egg Fry)', style: 'Telangana Style', veg: 'Non-Veg', description: 'Spiced egg fry' },
  { id: 220, section: 'Fry / Vepudu (Dry)', name: 'Chicken Sukka', style: 'Others', veg: 'Non-Veg', description: 'Dry roasted chicken with spices' },
  { id: 221, section: 'Podi, Pachadi & Pickles', name: 'Avakaya', style: 'Andhra Style', veg: 'Veg', description: 'Mango pickle, Andhra staple' },
  { id: 222, section: 'Podi, Pachadi & Pickles', name: 'Tomato Pachadi', style: 'Andhra Style', veg: 'Veg', description: 'Tangy tomato chutney' },
  { id: 223, section: 'Podi, Pachadi & Pickles', name: 'Nimmakaya Pickle', style: 'Andhra Style', veg: 'Veg', description: 'Lime pickle' },
  { id: 224, section: 'Podi, Pachadi & Pickles', name: 'Usirikaya Pickle', style: 'Andhra Style', veg: 'Veg', description: 'Gooseberry pickle' },
  { id: 225, section: 'Podi, Pachadi & Pickles', name: 'Gongura Pachadi', style: 'Andhra Style', veg: 'Veg', description: 'Sorrel-leaf chutney' },
  { id: 226, section: 'Podi, Pachadi & Pickles', name: 'Allam Pachadi', style: 'Andhra Style', veg: 'Veg', description: 'Ginger chutney' },
  { id: 227, section: 'Podi, Pachadi & Pickles', name: 'Pudina Pachadi', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Mint chutney' },
  { id: 228, section: 'Podi, Pachadi & Pickles', name: 'Kobbari Pachadi', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Coconut chutney' },
  { id: 229, section: 'Podi, Pachadi & Pickles', name: 'Dosakaya Pachadi', style: 'Andhra Style', veg: 'Veg', description: 'Yellow-cucumber chutney' },
  { id: 230, section: 'Podi, Pachadi & Pickles', name: 'Vankaya Pachadi', style: 'Andhra Style', veg: 'Veg', description: 'Roasted brinjal chutney' },
  { id: 231, section: 'Podi, Pachadi & Pickles', name: 'Pachi Mirchi Pachadi', style: 'Telangana Style', veg: 'Veg', description: 'Green-chilli chutney' },
  { id: 232, section: 'Podi, Pachadi & Pickles', name: 'Kandi Podi', style: 'Telangana Style', veg: 'Veg', description: 'Lentil spice powder' },
  { id: 233, section: 'Podi, Pachadi & Pickles', name: 'Karam Podi', style: 'Andhra Style', veg: 'Veg', description: 'Hot spice powder' },
  { id: 234, section: 'Podi, Pachadi & Pickles', name: 'Kobbari Podi', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Coconut spice powder' },
  { id: 235, section: 'Podi, Pachadi & Pickles', name: 'Nuvvula Podi', style: 'Telangana Style', veg: 'Veg', description: 'Sesame spice powder' },
  { id: 236, section: 'Podi, Pachadi & Pickles', name: 'Putnala Podi', style: 'Andhra Style', veg: 'Veg', description: 'Roasted-gram powder' },
  { id: 237, section: 'Podi, Pachadi & Pickles', name: 'Karivepaku Podi', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Curry-leaf powder' },
  { id: 238, section: 'Podi, Pachadi & Pickles', name: 'Idli Podi', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Spiced lentil powder for idli/dosa' },
  { id: 239, section: 'Podi, Pachadi & Pickles', name: 'Chicken Pickle', style: 'Godavari Style', veg: 'Non-Veg', description: 'Bhimavaram-style non-veg pickle' },
  { id: 240, section: 'Podi, Pachadi & Pickles', name: 'Prawn Pickle', style: 'Godavari Style', veg: 'Non-Veg', description: 'Spicy coastal prawn pickle' },
  { id: 241, section: 'Accompaniments', name: 'Appadam (Papad)', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Crisp lentil wafer' },
  { id: 242, section: 'Accompaniments', name: 'Fried Papad', style: 'Others', veg: 'Veg', description: 'Deep-fried papad' },
  { id: 243, section: 'Accompaniments', name: 'Masala Papad', style: 'Others', veg: 'Veg', description: 'Papad topped with onion-tomato' },
  { id: 244, section: 'Accompaniments', name: 'Roasted Papad', style: 'Others', veg: 'Veg', description: 'Flame-roasted papad' },
  { id: 245, section: 'Accompaniments', name: 'Vadiyalu (Sun-dried Fryums)', style: 'Andhra Style', veg: 'Veg', description: 'Crisp fried lentil fryums' },
  { id: 246, section: 'Accompaniments', name: 'Sabudana Vadiyalu', style: 'Andhra Style', veg: 'Veg', description: 'Sago fryums' },
  { id: 247, section: 'Accompaniments', name: 'Majjiga Mirapakayalu', style: 'Andhra Style', veg: 'Veg', description: 'Sun-dried buttermilk chillies' },
  { id: 248, section: 'Accompaniments', name: 'Aratikaya Vadiyalu', style: 'Godavari Style', veg: 'Veg', description: 'Raw-banana fryums' },
  { id: 249, section: 'Accompaniments', name: 'Plain Curd (Perugu)', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Fresh set yogurt' },
  { id: 250, section: 'Accompaniments', name: 'Boondi Raita', style: 'Others', veg: 'Veg', description: 'Yogurt with gram-flour pearls' },
  { id: 251, section: 'Accompaniments', name: 'Onion Tomato Raita', style: 'Others', veg: 'Veg', description: 'Yogurt with onion & tomato' },
  { id: 252, section: 'Accompaniments', name: 'Cucumber Raita', style: 'Others', veg: 'Veg', description: 'Yogurt with grated cucumber' },
  { id: 253, section: 'Accompaniments', name: 'Mixed Veg Raita', style: 'Others', veg: 'Veg', description: 'Yogurt with mixed vegetables' },
  { id: 254, section: 'Accompaniments', name: 'Pineapple Raita', style: 'Others', veg: 'Veg', description: 'Sweet pineapple yogurt' },
  { id: 255, section: 'Accompaniments', name: 'Mint Raita', style: 'Others', veg: 'Veg', description: 'Mint-flavored yogurt' },
  { id: 256, section: 'Accompaniments', name: 'Burani Raita', style: 'Hyderabadi', veg: 'Veg', description: 'Garlic-yogurt raita, served with biryani' },
  { id: 257, section: 'Accompaniments', name: 'Potato Chips', style: 'Others', veg: 'Veg', description: 'Crisp fried potato wafers' },
  { id: 258, section: 'Accompaniments', name: 'Banana Chips', style: 'Andhra Style', veg: 'Veg', description: 'Crisp fried plantain wafers' },
  { id: 259, section: 'Desserts & Sweets', name: 'Bobbatlu (Puran Poli)', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Lentil-jaggery stuffed sweet flatbread' },
  { id: 260, section: 'Desserts & Sweets', name: 'Pootharekulu', style: 'Godavari Style', veg: 'Veg', description: 'Atreyapuram paper-thin sweet' },
  { id: 261, section: 'Desserts & Sweets', name: 'Ariselu', style: 'Rayalaseema Style', veg: 'Veg', description: 'Rice-jaggery festive sweet' },
  { id: 262, section: 'Desserts & Sweets', name: 'Sunnundalu', style: 'Andhra Style', veg: 'Veg', description: 'Roasted urad-dal ladoo' },
  { id: 263, section: 'Desserts & Sweets', name: 'Bandar Laddu', style: 'Andhra Style', veg: 'Veg', description: 'Machilipatnam besan ladoo' },
  { id: 264, section: 'Desserts & Sweets', name: 'Kakinada Kaja', style: 'Godavari Style', veg: 'Veg', description: 'Layered syrup-soaked sweet' },
  { id: 265, section: 'Desserts & Sweets', name: 'Bellam Paramannam', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Jaggery rice pudding' },
  { id: 266, section: 'Desserts & Sweets', name: 'Chakkera Pongali', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Sweet rice pongal' },
  { id: 267, section: 'Desserts & Sweets', name: 'Boorelu (Poornalu)', style: 'Andhra Style', veg: 'Veg', description: 'Jaggery-lentil stuffed fried sweet' },
  { id: 268, section: 'Desserts & Sweets', name: 'Rava Laddu', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Semolina ladoo' },
  { id: 269, section: 'Desserts & Sweets', name: 'Double ka Meetha', style: 'Hyderabadi', veg: 'Veg', description: 'Saffron bread pudding' },
  { id: 270, section: 'Desserts & Sweets', name: 'Qubani ka Meetha', style: 'Hyderabadi', veg: 'Veg', description: 'Stewed apricot dessert' },
  { id: 271, section: 'Desserts & Sweets', name: 'Sheer Khurma', style: 'Hyderabadi', veg: 'Veg', description: 'Vermicelli & date milk pudding' },
  { id: 272, section: 'Desserts & Sweets', name: 'Gulab Jamun', style: 'Others', veg: 'Veg', description: 'Fried milk dumplings in syrup' },
  { id: 273, section: 'Desserts & Sweets', name: 'Rasmalai', style: 'Others', veg: 'Veg', description: 'Cheese discs in saffron milk' },
  { id: 274, section: 'Desserts & Sweets', name: 'Gajar ka Halwa', style: 'Others', veg: 'Veg', description: 'Carrot milk halwa' },
  { id: 275, section: 'Desserts & Sweets', name: 'Jalebi', style: 'Others', veg: 'Veg', description: 'Crisp syrup-soaked spirals' },
  { id: 276, section: 'Desserts & Sweets', name: 'Semiya Payasam', style: 'Pure-Veg Traditional', veg: 'Veg', description: 'Vermicelli milk kheer' },
  { id: 277, section: 'Desserts & Sweets', name: 'Basundi', style: 'Others', veg: 'Veg', description: 'Thickened sweetened milk' },
  { id: 278, section: 'Desserts & Sweets', name: 'Fruit Custard', style: 'Others', veg: 'Veg', description: 'Mixed fruit in custard' },
  { id: 279, section: 'Post-Meal', name: 'Fresh Cut Fruit Platter', style: 'Others', veg: 'Veg', description: 'Assorted sliced fruits' },
  { id: 280, section: 'Post-Meal', name: 'Seasonal Whole Fruits', style: 'Others', veg: 'Veg', description: 'Whole seasonal fruits' },
  { id: 281, section: 'Post-Meal', name: 'Watermelon Slices', style: 'Others', veg: 'Veg', description: 'Chilled watermelon slices' },
  { id: 282, section: 'Post-Meal', name: 'Pineapple Slices', style: 'Others', veg: 'Veg', description: 'Fresh pineapple slices' },
  { id: 283, section: 'Post-Meal', name: 'Musk Melon', style: 'Others', veg: 'Veg', description: 'Chilled musk melon' },
  { id: 284, section: 'Post-Meal', name: 'Papaya Slices', style: 'Others', veg: 'Veg', description: 'Fresh papaya slices' },
  { id: 285, section: 'Post-Meal', name: 'Sapota', style: 'Others', veg: 'Veg', description: 'Fresh chikoo fruit' },
  { id: 286, section: 'Post-Meal', name: 'Sweet Paan (Meetha Paan)', style: 'Others', veg: 'Veg', description: 'Betel leaf with sweet fillings' },
  { id: 287, section: 'Post-Meal', name: 'Calcutta Paan', style: 'Others', veg: 'Veg', description: 'Kolkata-style sweet paan' },
  { id: 288, section: 'Post-Meal', name: 'Chocolate Paan', style: 'Others', veg: 'Veg', description: 'Paan with chocolate filling' },
  { id: 289, section: 'Post-Meal', name: 'Gulkand Paan', style: 'Others', veg: 'Veg', description: 'Paan with rose-petal preserve' },
  { id: 290, section: 'Post-Meal', name: 'Banarasi Paan', style: 'Others', veg: 'Veg', description: 'Varanasi-style betel paan' },
  { id: 291, section: 'Post-Meal', name: 'Mukhwas', style: 'Others', veg: 'Veg', description: 'Mixed mouth freshener' },
  { id: 292, section: 'Post-Meal', name: 'Roasted Saunf', style: 'Others', veg: 'Veg', description: 'Roasted fennel seeds' },
  { id: 293, section: 'Post-Meal', name: 'Sugar-coated Fennel', style: 'Others', veg: 'Veg', description: 'Candied fennel mix' },
  { id: 294, section: 'Post-Meal', name: 'Dry Fruit Mukhwas', style: 'Others', veg: 'Veg', description: 'Dry-fruit mouth freshener' },
  { id: 295, section: 'Post-Meal', name: 'Kulfi', style: 'Others', veg: 'Veg', description: 'Traditional dense ice cream' },
  { id: 296, section: 'Post-Meal', name: 'Matka Kulfi', style: 'Others', veg: 'Veg', description: 'Kulfi set in clay pots' },
  { id: 297, section: 'Post-Meal', name: 'Falooda', style: 'Others', veg: 'Veg', description: 'Layered rose-vermicelli dessert' },
  { id: 298, section: 'Post-Meal', name: 'Ice Cream Cups', style: 'Others', veg: 'Veg', description: 'Assorted ice cream cups' },
]

